### ISSUE TITLE
jspm-cli removes `null` property

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1158] opened 2015-09-24 16:39 UTC
I defined `"files": ["file1.js", "file2.js"]` at the package.json root, and then I added `"files": null` inside `"jspm"` to overwrite it. The root files array is for npm publish, when I create bundles, but the inner jspm files should be empty. This all works, but when jspm modifies the package.json it removes the inner `"files": null` property. If I used everything correctly in the first place, then this should not happen.

**Comment by guybedford** [comment] 2015-09-25 13:14
Thanks.

**Comment by guybedford** [comment] 2015-10-08 14:33
I think this is a duplicate of https://github.com/jspm/jspm-cli/issues/1102, but let me know if I'm wrong.

**Closed by guybedford** 2015-10-08 14:33 UTC
Labels: bug

**Comment by neothemachine** [comment] 2015-10-08 14:41
I think this is not related, since I use a standard jspm property and jspmNodeConversion is only relevant when you publish directly to npm.

The issue here is, as soon as I do a `jspm install whatever` then it removes the `jspm.files` key if it is `null`.

**Comment by guybedford** [comment] 2015-10-08 14:42
@neothemachine I think they are related - even if `files` has a value it gets removed.
