### ISSUE TITLE
jspm bundle hangs on arithmetic bundle on beta.26

### ISSUE THREAD

**Issue by tyrsius** [jspm/jspm-cli#2048] opened 2016-08-25 21:15 UTC
I just upgraded from beta.22, where this command was working just fine

```
jspm bundle src/main.js - [src/**/*] - [devportal/**/*!text] dependencies.js --inject --skip-source-maps -d
```

It now hangs, and pegs the CPU until it is force killed. I tried downgrading back to beta.25, and it works fine. Its definitely a change between those two versions. It hangs though, and I am not sure where to start troubleshooting. This bug is still present in the latest beta.28

**Comment by dinoboff** [comment] 2016-08-25 23:44
Have you tried removing node_modules and reinstalling node packages?

**Comment by tyrsius** [comment] 2016-08-26 00:19
I have not, I will try firs thing in the morning. If that works, then there is another, much worse, problem.

**Comment by tyrsius** [comment] 2016-08-26 15:54
That did not work

**Comment by andershessellund** [comment] 2016-09-01 10:23
I experience the same problem. I think this is a performance regression. Bundling Angular2 now takes ~3 minutes on my mac, and memory consumption reaches about 800MB.

**Comment by guybedford** [comment] 2016-09-06 12:47
This is a consequence of moving to Babel unfortunately :(

**Comment by tyrsius** [comment] 2016-09-06 15:55
This is a significant consequence. What was the problem with the previous solution? I don't even understand exactly what changed, wasn't babel already being used for transpilation? What was moved to babel?

**Closed** 2016-09-30 11:52 UTC

**Comment by tyrsius** [comment] 2016-09-30 20:45
@guybedford Did you close this because beta29 solves it or because its old and you don't plan to revisit it?

**Comment by guybedford** [comment] 2016-10-02 18:52
@tyrsius it sounds like this was actually unrelated to the Babel upgrade path here. It may actually be a duplicate of https://github.com/systemjs/builder/issues/701.
