### ISSUE TITLE
Bundle command should be indifferent to where you run it from

### ISSUE THREAD

**Issue by Vanuan** [jspm/jspm-cli#888] opened 2015-06-27 19:34 UTC
Currently, jspm bundle treats module name and file name as the same.
This way, I'm forced to run jspm bundle from the same directory as http server.
Example:

    ./src/app.js
    jspm bundle src/app ./build/app.js
    ./build/app.js

This way, I would have to do `System.import("src/app")` from my index.html, and as a result `./build/src/app.js` would not be found. If I do `System.import("app")`, the script file would be loaded, but module would not be run.

What am I doing wrong?

**Comment by topheman** [comment] 2015-06-28 00:14
Hie @Vanuan , I have the same kind of problem.

I have the following folder organization :

* build
* jspm_packages
* node_modules
* src
  * app
    * bootstrap.js
    * ...
  * index.html
* package.json
* gulp.file
* jspm.config.js

A gulp task serves the `src` folder on `/` and the `jspm_packages` on `/jspm_packages/`. 
In the `jspm.config.js` file, `"baseURL": "./"`.
In `app/index.html` (served in http on `/`) : `System.import('app/bootstrap.js')`

Since, like you said, jspm is module name based, when I build, I can't do the following :
`jspm bundle app/bootstrap ./.tmp/scripts/app.bootstrap.build.js` , the build fails because it can't find the file.

If I `jspm bundle src/app/bootstrap ./.tmp/scripts/app.bootstrap.build.js`, it works, but then, I'll have to change to `System.import('src/app/bootstrap.js')`, which won't work in production or staging.

I even tried `jspm init -p`, to have the `jspm_packages` folder and the `jspm.config.js` file inside `src` but it ends up being the same problem.

Am I doing something wrong ?

PS : I'm on the latest systemjs version (v0.18.2) and the latest builder (v0.12.1). To get a better idea of the folder structure : https://github.com/topheman/angular-es6-jspm (the build part is not pushed yet since it's not finished but it could help get a better understanding)

**Comment by Vanuan** [comment] 2015-06-28 00:25
The workaround I used:
```
// config.js
"paths": { "*": "src/*.js" }
// index.html
System.import('app/index')
// bundle to build/src/app.js
jspm bundle app ./build/src/app.js
```

**Comment by topheman** [comment] 2015-06-28 00:45
This does work, but in dev mode, requests are made to `/src/app/..` not `/app/..` (not the best).

Moreover I still can't make the self executing bundle work `jspm bundle-sfx app/bootstrap ./.tmp/scripts/app.bootstrap.build.js` , could you ?

Error : `AssertionError: missing path`

**Comment by guybedford** [comment] 2015-06-28 18:36
The baseURL is always the folder set as the baseURL in the package.json `directories.baseURL` or the same folder as the package.json. Running `jspm bundle` from any folder within the project will use the same baseURL.

The baseURL is the _reference point_ for bundling. That is the bundle contains module names that are relative to this path.

I'm not sure why you want the name of the bundle module to be the same as the name of the module that is the entry point of the bundle. There's nothing wrong with them being different module names.

If you want `System.import('app')` to work, this is what bundle config is for:

```javascript
System.config({
  bundles: {
    'dist/bundle.js': ['app']
  }
});
```

The above says that the module located at `dist/bundle.js` (`System.import('dist/bundle.js')`) contains the module `app` relative to the baseURL.

**Comment by topheman** [comment] 2015-06-28 19:47
Thanks for the answer @guybedford , I don't think it's a bundles config issue (I only have one entry point and one output bundle). It's more about having the same `System.import('app/bootstrap')` whether we're on dev or prod (but as you pointed out, it's not *that* important - moreover, I'll have routines that will change that markup).

If I use the workaround pointed out by @Vanuan above, for me, it's like :

```
// config.js
"paths": { "app/*": "src/app/*.js" }
// index.html
System.import('app/bootstrap.js')
// bundle to .tmp/scripts/app.bootstrap.build.js
jspm bundle app/bootstrap.js ./.tmp/scripts/app.bootstrap.build.js
```

But I still can't `jspm bundle-sfx app/bootstrap.js ./.tmp/scripts/app.bootstrap.build.js` like in this issue : https://github.com/jspm/jspm-cli/issues/889 (same error)

```
err  AssertionError: missing path
         at Module.require (module.js:363:3)
         at require (module.js:384:17)
         at /Users/Tophe/.nvm/versions/node/v0.12.0/lib/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:157:16
         at Array.forEach (native)
         at wrapSFXOutputs (/Users/Tophe/.nvm/versions/node/v0.12.0/lib/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:156:26)
         at /Users/Tophe/.nvm/versions/node/v0.12.0/lib/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:136:14
         at lib$rsvp$$internal$$tryCatch (/Users/Tophe/.nvm/versions/node/v0.12.0/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/Tophe/.nvm/versions/node/v0.12.0/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/Users/Tophe/.nvm/versions/node/v0.12.0/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/Users/Tophe/.nvm/versions/node/v0.12.0/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at process._tickCallback (node.js:355:11)
```

Note : I'm on jspm-cli latest (tried the solution you wrote down - `npm install -g -f jspm@beta`) :

```
$ jspm --version
0.16.0-beta.3
$ npm install -g -f jspm@beta
$ jspm --version
0.16.0-beta.3
```

Note : I'm sorry this bug might become a duplicate of https://github.com/jspm/jspm-cli/issues/889 - feel free to answer the `jspm bundle-sfx` part on the other one.

**Comment by guybedford** [comment] 2015-06-29 17:56
Sure, that seems fine. Ok I will close this as a duplicate of #889 then. Will aim to push out that patch very soon.

**Closed by guybedford** 2015-06-29 17:56 UTC
