### ISSUE TITLE
[0.17.0-beta.21] Module must be loaded as AMD or CommonJS

### ISSUE THREAD

**Issue by quentind** [jspm/jspm-cli#1915] opened 2016-06-14 19:23 UTC
When creating a self-executing bundle with jspm `0.17.0-beta.18` everything works fine.
With `0.17.0-beta.21`, the bundle is created, but at runtime in the browser I get the `Module must be loaded as AMD or CommonJS` error.

Not sure how I can help diagnose the problem or if one specific module is causing this.

**Comment by guybedford** [comment] 2016-06-14 21:09
Thanks for reporting, can you perhaps try removing imports from the main
entry point to try and isolate the issue? Otherwise if you can share a full
replication happy to look into it too.

**Comment by frederikschubert** [comment] 2016-06-15 01:55
When testing [this](https://github.com/jspm/registry/pull/914) PR the same issue popped up. It was a clean project.
To replicate:
```shell
jspm init # Choose all defaults
jspm install npm:bootstrap@3 -o "{
  \"main\": \"dist/js/bootstrap\",
  \"files\": null,
  \"jspmNodeConversion\": false,
  \"shim\": {
    \"dist/js/bootstrap\": {
      \"deps\": [
        \"jquery\",
        \"tether\"
      ],
      \"exports\": \"$\"
    }
  },
  \"dependencies\": {
    \"jquery\": \"*\",
    \"tether\": \"github:HubSpot/tether@^1.1.1\"
  }
}"
```
Then create the following `src/app.js`:
```javascript
import bootstrap from "bootstrap";

console.log(bootstrap);
```
And this index.html:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Test</title>
        <meta charset="UTF-8">
        <link href="css/style.css" rel="stylesheet">
        <script src="build.js">
    </head>
    <body>
    
    </body>
</html>
```
Where build.js is the output of the following command:
```shell
jspm build src/app.js
```

**Comment by quentind** [comment] 2016-06-15 08:43
I tried removing every import for the entry point and I was getting the same error untill there was no import left to remove.

After that I cleaned up the `jspm_packages` folder and re-installed everything which seem to fix the issue. But that doesn't seem to match @frederikschubert's case.

Now, I can't reproduce the issue even be rolling back to my config using `0.17.0-beta.18`.

**Comment by frederikschubert** [comment] 2016-06-15 08:56
I created the project with beta.12 and then did the bundling with beta.21. Maybe that's where the error comes from? I will try to narrow it down tomorrow!

**Comment by jackfranklin** [comment] 2016-06-15 09:56
I also saw this error yesterday; the built bundle in the browser worked completely fine, but I saw this error still. I should be able to get a repo up with the issue in soon.

**Comment by quentind** [comment] 2016-06-15 10:00
I actually could reproduce the issue.
This occurs for me only when enabling rollup optimizations.

**Comment by jackfranklin** [comment] 2016-06-15 10:03
`jspm bundle app.js` works fine for the browser, no errors.

`jspm build app.js` works fine for the browser, but I see the error given above.

**Comment by guybedford** [comment] 2016-06-15 10:31
Ok yes this is a Rollup integration bug. Fixed in https://github.com/systemjs/builder/commit/91a4271a63ce82ebafef05bd8594e5f43f0f9b33.

**Comment by guybedford** [comment] 2016-06-15 16:02
Released in 0.17.0-beta.22.

**Closed by guybedford** 2016-06-15 16:02 UTC
Labels: bug, fixed pending release

**Comment by quentind** [comment] 2016-06-15 16:33
Getting `ReferenceError: process is not defined` at runtime after updating to `0.17.0-beta.22`, with or without rollup (nothing else changed from previous issue).

**Comment by guybedford** [comment] 2016-06-18 18:15
@quentind `process` is undefined in the jspm context, unless explicitly loading npm package code that has `globals` configuration added to set process. I would need to know what code it is that is giving the error though to help further.

**Comment by martinmicunda** [comment] 2016-11-26 19:40
@guybedford I am getting exactly same error. I am able to successfully create sfx bundle with `jspm 0.17.0-beta.32` but then in run time I am getting `Module must be loaded as AMD or CommonJS`. I debugged the code and the cause of the issue is when I want to import `core-js` library (same issue when I want to import `babel-polyfill`).

*jspm.config.js*
```js
SystemJS.config({

    transpiler: "plugin-babel",
    babelOptions: {
        "stage": 1,
        "plugins": [
            "babel-plugin-transform-decorators-legacy"
        ]
    },
    packages: {
        "app": {
            "main": "main.js",
            "format": "esm",
            "meta": {
                "*.js": {
                    "loader": "plugin-babel"
                },
                "*.html": {
                    "loader": "text"
                },
                "*.json": {
                    "loader": "json"
                }
            }
        }
    },
});
SystemJS.config({
    packageConfigPaths: [
        "npm:@*/*.json",
        "npm:*.json",
        "github:*/*.json"
    ],
    map: {
        "core-js": "npm:core-js@2.4.1",
        "angular": "github:angular/bower-angular@1.5.6"
        .....
  }
```

*main.js*
```js
import 'core-js'; --> this cause issue when I try to load sfx bundle
import 'angular';
```

**Comment by vcernomschi** [comment] 2017-08-10 12:14
I've got this error for v0.17.0-beta.42

**Comment by aluanhaddad** [comment] 2017-08-10 16:53
@vcernomschi are you getting the error when running the output of your build or just in general?

**Comment by vcernomschi** [comment] 2017-08-10 17:22
Hi @aluanhaddad, 

I am getting this error in browser console, while running application. So 'jspm build' has been executed successfully.
