### ISSUE TITLE
Wrapping installed package causes redeclaration of variable

### ISSUE THREAD

**Issue by MikeKovarik** [jspm/jspm-cli#1576] opened 2016-02-29 16:22 UTC
Hi,
While working on chrome packaged app I noticed the module `http-node` didn't work and threw this error.

```
Uncaught (in promise) Error: Identifier 'Buffer' has already been declared
```

I managed to trace the error down to two files ([_http_outgoing.js](https://github.com/jscissr/http-node/blob/master/_http_outgoing.js), [_http_client.js](https://github.com/jscissr/http-node/blob/master/_http_client.js)) being strangely wrapped by jspm during the module installation I guess.
For example the code of `_http_outgoing.js` gets wrapped into this self invoking function with `Buffer` but constant of the same name is defined a few lines below.

```
(function(Buffer, process) {
  'use strict';
  const assert = require('assert').ok;
  ...
  const internalUtil = util;
  const Buffer = require('buffer').Buffer;
  ...
  ...
})(require('buffer').Buffer, require('process'));
```

This has happened in a clean new project using jspm 0.16.25 just by installing the module.

```
jspm install npm:http-node
```

I also tried in with 0.17 beta 9 where installation won't modify those files right away but the same prolem occurs when bundling. Only in this case it's not wrapped in a function but the `Buffer` variable gets declared beforehand anyway.

```
System.registerDynamic("npm:http-node@1.0.0/_http_outgoing.js", ["assert", "stream", "timers", "util", "buffer", "./_http_common", "process", "buffer/global"], true, function($__require, exports, module) {
  "use strict";
  var process = $__require("process"),
      Buffer = $__require("buffer/global");
  var define;
  var global = this;
  var GLOBAL = this;
  const assert = $__require('assert').ok;
  ..
  const internalUtil = util;
  const Buffer = $__require('buffer').Buffer;
```

**Comment by guybedford** [comment] 2016-03-03 14:59
Thanks, I've added a fix for this in jspm 0.17 in https://github.com/jspm/npm/commit/ad4d92cd498293e7c6fd967224d616e46f41002a pending release.

**Comment by guybedford** [comment] 2016-03-10 08:36
Released in 0.17.0-beta.10.

**Comment by metrorailings** [comment] 2018-02-19 05:35
I was able to reproduce this issue in the latest version of 0.17 (0.17.0-beta.47)

**Comment by karthicks** [comment] 2018-03-25 05:53
@guybedford , @metrorailings ,

I too was able to reproduce this with the `0.17.0-beta.47`of `jspm`. Here's one way to repro this issue:

* Install socket.io@2.0.4, by running `jspm i npm:socket.io@2.0.4`
* Install socket.io-client@2.0.4, by running `jspm i npm:socket.io-client@2.0.4`
* Create a dependencies.js file that simply imports the client, like so: `import * as io from 'socket.io-client';`
* Create a jspm bundle for it, like so: `jspm build dependencies.js dist/js/dependencies.js -id`
* Try to load the bundled file, using `SystemJS`, like so: `SystemJS.import('dist/js/dependencies.js)`.

Can we re-open this issue or create a new one? As I noted in the `gitter.im` channel, the problem is that the generated code declares a `Buffer` variable, which is then followed by a `Buffer` const declaration, which is a no-no, in es6:
```
$__System.registerDynamic('1e7', ['1e8', '1e1', '1e2', '1dd', '1aa', '1a8', '1e3', '1df', '1e4',     '1e0', '13f', '1ac'], true, function ($__require, exports, module) {
  ...
  var process = $__require('13f'), Buffer = $__require('1ac');
  ...
  const Buffer = safeBuffer.Buffer;
```
Not sure what the `Buffer` variable declaration refers to, but if it's jspm-specific, perhaps it could be prefixed as such?

Regards,
Karthick

**Comment by guybedford** [comment] 2018-05-03 21:51
Reopening. It sounds like a similar fix for detecting Buffer usage in the source is needed to avoid the conflict. Note running the source through a const -> var transformer may be one hack to make it run :)

**Closed** 2019-04-24 02:18 UTC
Labels: 👍 fixed pending release
