### ISSUE TITLE
cannot load font-awesome css in sfx-bundle

### ISSUE THREAD

**Issue by pdeva** [jspm/jspm-cli#1412] opened 2016-01-11 01:00 UTC
Using JSPM 0.6.19.

I am able to load all the other app-local modular css fine.
It seems the issue is with loading css in 3rd party bundles.
It only occurs when using a sfx-bundle. 

in my main.js file, I have:
```
import 'font-awesome/css/font-awesome.min.css!';
```

I see this error in the console:
```
GET http://127.0.0.1:8080/jspm_packages/npm/font-awesome@4.5.0/fonts/fontawesome-webfont.ttf?v=4.5.0 404 (Not Found)
```
As you can see it is trying to load the font-awesome css from the jspm_packages folder instead of from the sfx-bundle file.

If i however load an app-local css like:
```
import './topNavbar.css!';
```
that is properly loaded from the sfx-bundle file and works fine.

Jspm dependencies are:

```
"dependencies": {
      "css": "github:systemjs/plugin-css@^0.1.20",
      "font-awesome": "npm:font-awesome@^4.5.0",
}
```

**Comment by guybedford** [comment] 2016-01-11 15:59
Thanks, I just tried this case exactly and wasn't able to replicate at all. Is there anyway you can share a test project or exact replication instructions for this?

**Comment by guybedford** [comment] 2016-01-11 16:19
Duplicate of https://github.com/jspm/jspm-cli/issues/1411, will be fixed in the next patch shortly.

**Closed by guybedford** 2016-01-11 16:19 UTC

**Comment by yiqingj** [comment] 2016-03-17 16:47
I think this is actually related to https://github.com/systemjs/plugin-css/issues/61. which doesn't seem to be solved yet.
