### ISSUE TITLE
bundles error with 'exports is not defined' on html imports

### ISSUE THREAD

**Issue by MoonStorm** [jspm/jspm-cli#2270] opened 2017-03-29 19:30 UTC
When attempting to bundle html files for production, I get the following construct in the js file: 
```
System.register("app/components/component.html", [], function (_export, _context) {
  "use strict";
  return {
    setters: [],
    execute: function () {
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.__useDefault = true;
      exports.default = "<div>....</div>";
    }
  };
});
```
Bundles get generated but they fail with an 'exports is not defined' error when referenced in the browser.

The dev/build config uses the ``typescript plugin`` and the ``text plugin``, both working fine otherwise.

**Comment by guybedford** [comment] 2017-03-30 11:26
This seems like a duplicate of https://github.com/systemjs/plugin-text/issues/47, moving discussion there.

**Closed by guybedford** 2017-03-30 11:26 UTC
