### ISSUE TITLE
Automatically loading babel-polyfill

### ISSUE THREAD

**Issue by priyatam** [jspm/jspm-cli#535] opened 2015-02-23 00:17 UTC
The project generated by `jspm init` with babel does not transpile generators, among other ES6 features, and I get the following error:

    ReferenceError: regeneratorRuntime is not defined

Turns out, Babel includes a [polyfill](http://babeljs.io/docs/usage/polyfill/#usage-in-browser) that includes a custom regenerator runtime and core.js that is required to enable _all_ ES6 features. I tried to add it manually in main.js, like so

    import * as p from 'babel-polyfill'

Jspm can't find it though I can see it under my local `jspm_packages`.What am I missing?

**Comment by guybedford** [comment] 2015-02-23 08:56
Try including the polyfill with a script tag in the page.

**Comment by priyatam** [comment] 2015-02-23 09:30
Thanks, that [worked](https://github.com/priyatam/es6-live/blob/master/index.html#L17). 

Ideally, It would be nice to include the polyfill by default in dev. If you can point me to the right code I can send a pull request.

**Comment by guybedford** [comment] 2015-02-23 09:31
How would we reliably know when it is needed?

**Comment by priyatam** [comment] 2015-02-23 09:45
Good point, but we don't have to know during dev. I chose jspm over a dozen other "es6 transpiler setups" because none of them worked out of the box. Compare that to Cofffeescript or Clojurescript, our workflows are fairly stable.

**Comment by guybedford** [comment] 2015-02-23 09:51
Specifically, are you saying you'd want to always include it in the browser?

**Comment by priyatam** [comment] 2015-02-23 09:54
Yes.

**Comment by guybedford** [comment] 2015-02-23 09:55
Sure, we are going to be doing some work on the polyfill / runtime workflows soon to make sure they are more seamless from development to production. Will leave this issue up to track this part of that.

**Comment by jhabdas** [comment] 2015-03-08 01:02
Including the polyfill with a script tag in the page [worked for me](https://github.com/jhabdas/xanthippe/blob/v1.0.0/dist/index.html#L3) as well.

**Comment by lookfirst** [comment] 2015-03-15 01:34
I don't want to include the polyfill as a script tag. When I import it, I get this error in the browser:

```
Potentially unhandled rejection [3] TypeError: Error loading "jspm_packages/babel-polyfill" at http://localhost:9000/jspm_packages/babel-polyfill.js
Error loading "jspm_packages/babel-polyfill" from "app/boardgame/main" at http://localhost:9000/app/boardgame/main.js
AMD module jspm_packages/babel-polyfill did not define
    at x.e.instantiate (http://localhost:9000/jspm_packages/system.js:1:15566)
    at x.e.instantiate (http://localhost:9000/jspm_packages/system.js:1:18645)
    at http://localhost:9000/jspm_packages/es6-module-loader.js:7:14452
    at O (http://localhost:9000/jspm_packages/es6-module-loader.js:7:7439)
    at K (http://localhost:9000/jspm_packages/es6-module-loader.js:7:7071)
    at y.when (http://localhost:9000/jspm_packages/es6-module-loader.js:7:10745)
    at D.run (http://localhost:9000/jspm_packages/es6-module-loader.js:7:11854)
    at a._drain (http://localhost:9000/jspm_packages/es6-module-loader.js:7:1740)
    at drain (http://localhost:9000/jspm_packages/es6-module-loader.js:7:1394)
    at MutationObserver.b (http://localhost:9000/jspm_packages/es6-module-loader.js:7:3302)
```

It feels like there should be a better way.

**Comment by msegado** [comment] 2015-03-15 02:32
@lookfirst - as I understand it this may be fixed by the upcoming changes (see above). In the meantime, I ran into this same issue (while trying to use jspm-karma) and there is indeed a better way =) The problem is that the browser polyfill doesn't support loading via AMD, but it looks enough like AMD that SystemJS autodetects it as such. You can force SystemJS to treat it as a global module instead by using the following in your `config.js`: 

```javascript
System.config({
  "meta": {
    "jspm_packages/babel-polyfill": {
      "format": "global"  // Prevents misdetection as AMD
    }
  }
});
```

**Comment by lookfirst** [comment] 2015-03-15 03:20
@msegado My hacky solution is to just include babel has a npm dependency in my package.json jspm dependencies. That effectively sets up the map{} configuration for me. I discovered the hard way that babel from github:babel/babel is different than babel from npm:babel.

**Comment by guybedford** [comment] 2015-03-17 12:22
This is fixed in the upcoming release, which uses the runtime transformation.

**Closed** 2015-03-24 23:36 UTC

**Comment by LeDominik** [comment] 2015-03-25 12:48
Sadly, at least for me it doesn't quite work out with 0.15.0-beta. I'm using JSX and in a JSX File the `Object.assign()` functionality that needs a Polyfill (or some transform). My `package.json` is 
```
{
  "jspm": {
    "directories": {
      "lib": "."
    },
    "dependencies": {
      "react": "github:reactjs/react-bower@^0.13.1"
    },
    "devDependencies": {
      "babel": "npm:babel@^4.7.16",
      "babel-runtime": "npm:babel-runtime@^4.7.16",
      "jsx": "github:floatdrop/plugin-jsx@^1.1.0"
    }
  }
}
```

Everything seems to be working fine, including ES6 modules. Just the `Object.assign()` doesn't like me and of course there's still the ugly ! in the import necessary for JSX-transform... I'm sure I'm doing something wrong, however the good old trick using `<script...` importing is no longer as easy with babel hidden in the dependency-tree.

**Comment by guybedford** [comment] 2015-03-25 12:54
Thanks - it may be worth manually importing core-js for the polyfills. I've created https://github.com/jspm/jspm-cli/issues/615 to investigate the polyfill path more carefully.

**Comment by LeDominik** [comment] 2015-03-25 13:13
Thanks; tried that but not much fun :-1:  Will keep trying, I can literally **see** that `Object.assign()` is right there in core-js but can't get it into global namespace.

**Comment by guybedford** [comment] 2015-03-25 13:25
@LeDominik I just tested `Object.assign` and it is working fine for me.

Note that jspm adds the configuration:

```javascript
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
```

into the config.js file. It is important not to override this.

**Comment by olanod** [comment] 2015-04-20 17:02
`Object.assign` works for me, but not Array find/findIndex which is supposed to come in the runtime as well. Do you know about this?

**Comment by guybedford** [comment] 2015-04-20 17:09
@olanod it's definitely working fine for me - you need to ensure that the file is a module with ES6 module syntax.

**Comment by olanod** [comment] 2015-04-20 17:16
I edited my comment. So if I understand right, if I want `someArray.find()` to work I need to include the polyfill as a script tag before anything? No way of make it work without the external script?

**Comment by guybedford** [comment] 2015-04-20 17:19
This sounds like a Babel-specific issue. I guess, Babel doesn't know that the object you're dealing with is an Array and not just an object with an arbitrary find method. You can manually import from core-js - 

```javascript
import $ from 'core-js/library/modules/$';
$.core.Array.find; //etc.
```

Or alternatively trigger the `Array.find` path as you mentioned above.

**Comment by DominicBoettger** [comment] 2015-05-27 15:34
So how are you loading the Polyfill files?
I am using Babel 5.2.15 and did not find out how to load the stuff.

**Comment by guybedford** [comment] 2015-05-27 15:38
This should work via `jspm install core-js` and `import 'core-js/shim'`?

**Comment by lookfirst** [comment] 2015-05-27 15:44
I feel like this process could be automated somehow. Either Babel or jspm or SystemJS... not really sure where it would land, but if any one of those saw one of the ES6 new methods in the code, it would include the polyfill support for it automatically...

**Comment by DominicBoettger** [comment] 2015-05-27 15:56
@guybedford Very good! That worked for me. Thanks a lot.

**Comment by rlovtangen** [comment] 2015-08-24 08:19
Not sure if I did the right thing, but after reading https://babeljs.io/docs/usage/polyfill/ which says to `require("babel/polyfill");` my intuition was to try
````
import BabelPolyfill from 'babel/polyfill'
````
and it worked. The name `BabelPolyfill` doesn't matter, though, could be anything.
At least this solved my problem with missing String.startsWith in IE10.

**Comment by msegado** [comment] 2015-08-24 18:23
@rlovtangen, thanks for the heads-up; good to know that works. I expect it should work fine if you leave out the binding entirely, too:
```js
import 'babel/polyfill';
```

**Comment by rlovtangen** [comment] 2015-08-25 07:17
You're absolutely right, @msegado. Thanks!

**Comment by vanthome** [comment] 2015-08-25 20:37
@rlovtangen For me it does not work. I have this:

Source file:

`import 'babel/polyfill';`

project package.json:

    "devDependencies": {
      "babel": "npm:babel-core@^5.8.22",
      "babel-runtime": "npm:babel-runtime@^5.8.20",
      "core-js": "npm:core-js@^1.1.0"
    },

config.js:

    babelOptions: {
      "optional": [
        "runtime"
      ]
    },

any idea?

**Comment by rlovtangen** [comment] 2015-08-26 06:41
@vanthome Looks quite similar to my setup. My devDependencies is exactly the same except I have core-js 1.1.1.
My config.js:
````
System.config({
  baseURL: "/assets",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  map: {
    "babel": "npm:babel-core@5.8.22",
    "babel-runtime": "npm:babel-runtime@5.8.20",
    "core-js": "npm:core-js@1.1.1",
    ...
````
Do you have the file `npm/babel-core@5.8.22/polyfill.js` under jspm_packages? I would guess that's the actual file. If not, try `jspm install`
