### ISSUE TITLE
buffer@4.9.1.js 404

### ISSUE THREAD

**Issue by nomve** [jspm/jspm-cli#2069] opened 2016-09-09 08:00 UTC
Hi,

I was checking something and made a test directory with the latest jspm@beta (`0.17.0-beta.28`). Trying to load the page I get a 404 for `buffer@4.9.1.json`. The package is not there.

```
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3333/path/to/jspm_packages/npm/buffer@4.9.1.json
	
	Error loading http://localhost:3333/path/to/jspm_packages/npm/buffer@4.9.1.json
	Error loading http://localhost:3333/path/to/jspm_packages/npm/systemjs-plugin-babel@0.0.14/systemjs-babel-browser.js as "systemjs-babel-build" from http://localhost:3333/path/to/jspm_packages/npm/systemjs-plugin-babel@0.0.14/plugin-babel.js
	Error loading http://localhost:3333/path/to/source/main.js
```

There are no problems when bundling. I've manually downgraded `"npm:systemjs-plugin-babel` to `0.0.13` and it doesn't happen anymore.

**Comment by guybedford** [comment] 2016-09-13 16:49
Tracking as a duplicate of https://github.com/systemjs/plugin-babel/issues/59.

**Closed by guybedford** 2016-09-13 16:49 UTC
