### ISSUE TITLE
npm packages with `"format": "es6"` get wrong annotations on node transforms 

### ISSUE THREAD

**Issue by zcregan** [jspm/jspm-cli#626] opened 2015-03-27 04:29 UTC
We have an npm package that is all es6. We've added `"format": "es6"`to our package.json. Our package directory structure has a bunch of directories containing index.js files.
```
package/
--components/
----component1/
------index.js
----component2/
------index.js
```
JSPM correctly identifies this structure and generates `component1.js` and `component2.js` which look like this:
```
"format es6";
module.exports = require('./component1/index');
```
I assume `"format es6";` was added because of the package.json, but obviously this won't work now because SystemJS doesn't apply the cjs transforms.

**Comment by guybedford** [comment] 2015-03-27 11:45
`format` refers to the module format, and SystemJS only gives ES6 treatment to ES6 modules not ES6 scripts.

What you have there are ES6 scripts, which aren't transpiled by jspm. Rather you need to handle the lifecycle of these manually.

The options are:
1. Run a custom prepublish step to convert to CommonJS
2. Use ES6 modules instead of CommonJS in ES6

Use (1) if you want to support normal npm installs. Use (2) for jspm usage.

**Comment by zcregan** [comment] 2015-03-27 21:31
I put together an example https://github.com/zcregan/npm-es6-demo

If you install it into a jspm project `jspm install github:zcregan/npm-es6-demo` and then compare `jspm_packages/github/zcregan/npm-es6-demo@master` to the actual github repo.

jspm generates the file `npm-es6-demo@master/submodule.js` which basically redirects you to `npm-es6-demo@master/submodule/index.js`. The problem is with that generated file.
```
"format es6";
module.exports = require('./submodule/index');
```
That `"format es6";` annotation breaks the file.

**Comment by guybedford** [comment] 2015-03-27 21:40
@zcregan this is by design - don't use `format: 'es6'` if your repo contains CommonJS.

**Comment by guybedford** [comment] 2015-03-27 21:41
`format` really means `moduleFormat`.

**Comment by zcregan** [comment] 2015-03-27 21:42
My repo doesn't contain CommonJS. Jspm generated that CommonJS file.

**Comment by guybedford** [comment] 2015-03-27 22:11
Right - so by setting `registry: 'npm'` it is treating it like a NodeJS project and doing the automatic directory require creation. Remove the `registry: 'npm'` part to disable this treatment.

**Comment by guybedford** [comment] 2015-03-27 22:12
Alternatively you can set `jspmNodeConversion: 'false'` to tell the npm registry endpoint not to do any conversion.

**Comment by zcregan** [comment] 2015-03-27 22:48
I actually want the automatic directory require creation though, just without the `"format es6"; ` at the top of the generated file.

Maybe what we're trying to do is just too strange... We have this big toolkit that we use for projects internally and we'll also be sharing it to select 3rd parties in the near future. It's on our companies own private npm repo unfortunately so I'm not able to share it. But what we're aiming to do is write the entire toolkit in es6. It's still an npm package though, and it uses npm dependencies. And the hope was to write our module imports with the same path resolution as node's require. Then we have two npm publish processes. One compiles the es6 code to es5 and CommonJS and publishes to an "es5 compatibility" npm package. The other just leaves the es6 code as is and publishes to our es6 npm package. Internally, all our projects that use this toolkit are jspm projects that install the es6 version of our toolkit, and then the projects handle the es6 compilation through jspm upstream from the toolkit.

This is all working perfectly! Except for the fact that we can't go `import 'submodule'`. We have to go `import 'submodule/index'`.

**Comment by zcregan** [comment] 2015-03-27 22:53
Everything would work perfectly if `"format es6"; ` wasn't prepended to that automatic directory require file.

**Comment by zcregan** [comment] 2015-03-27 22:59
Would it make sense for jspm to generate that automatic directory require file in es6 module syntax if the package.json was marked with "format es6"?

So in my previous example:
```
export * from 'submodule/index';
```
I wouldn't mind making a PR if you think that actually make sense.

**Comment by guybedford** [comment] 2015-03-29 17:58
@zcregan that would certainly be a possibility, but I'm hesitant to start adding ES6 behaviours to the Node conversion layer as we have to follow the lead of how Node decides to implement ES6 modules here rather and support that. If we start adding behaviours users rely on here that then don't match up with how things end up working for ES6 modules and Node in future, then we hit issues.

I would actually suggest here just loading the CJS-converted version entirely in jspm for now.

**Comment by zcregan** [comment] 2015-04-01 19:03
@guybedford yeah you're right.

On a somewhat related note, I also realized that with `format es6` jspm doesn't detect node built-in module dependencies...  Do you think it would make sense for jspm to handle this?

**Comment by guybedford** [comment] 2015-04-01 19:58
It could potentially be an option for the ES6 requires yes. I've created an issue at https://github.com/jspm/npm/issues/53. Again my worry though is that Node really does implement this functionality, and that there aren't bad assumptions being made.

**Comment by guybedford** [comment] 2015-04-19 23:50
Closing this, as we really can't make assumptions about how npm will treat ES6 modules.

Either transpile into CommonJS and use the Node/npm conventions, or stick with jspm conventions explicitly. If we want to expect a subset of behaviours we create around Node and ES6 to be supported like this, we need to combine that effort with active sharing of those conventions with the Node community.

**Closed by guybedford** 2015-04-19 23:50 UTC

**Comment by hmalphettes** [comment] 2015-09-14 10:22
Now that nodejs-v4 is out I have been using a lot of 'ES6 scripting' along with CommonJS requires.

jspm/systemjs has been a fantastic for running this code in the latest Goog Chrome.
I was hoping that the bundle builder and systemjs could be instructed to transpile ES6 into ES5 along with the CJS requires.

Would it be a good idea to revisit this issue now that CJS-require combined with ES6 scripting is the mainstream style for nodejs developers?

Otherwise I'll settle on transpiling to ES5 before I call jspm to bundle the files.

**Comment by guybedford** [comment] 2015-09-17 16:25
@hmalphettes certainly we are aiming to cater to these workflows - separating transpilation from the module format of ES6 is on the roadmap for SystemJS (https://github.com/systemjs/systemjs/issues/579).

**Comment by hmalphettes** [comment] 2015-09-22 07:34
Thanks and thanks for the link! Calling `babel` first and then `jspm bundle` works for now.
