### ISSUE TITLE
Weird edge case when bundling in parallel with minification on

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#806] opened 2015-06-04 15:48 UTC
I have the following module, `raven`:

``` js
(define("raven", function() {}))
```

When I try to bundle this module twice in parallel:

``` js
var jspm = require('jspm');
var builder = new jspm.Builder();
var bundleConfigs = [
    ['raven', 'a'],
    ['raven', 'b']
];

var createBundle = function (bundleConfig) {
    var moduleExpression = bundleConfig[0];
    var outName = bundleConfig[1];
    return builder.build(moduleExpression, null, { minify: true });
};

Promise.all(bundleConfigs.map(createBundle))
    .catch(function (error) {
        console.error(error);
    });
```

I get:

```
$ node bundle
{ message: 'Unexpected token: punc ())',
  filename: null,
  line: 4,
  col: 1,
  pos: 73,
  stack: 'Error\n    at new JS_Parse_Error (/Users/OliverJAsh/Development/frontend/node_modules/jspm/node_modules/uglify-js/lib/parse.js:196:18)\n    at js_error (/Users/OliverJAsh/Development/frontend/node_modules/jspm/node_modules/uglify-js/lib/parse.js:204:11)\n    at croak (/Users/OliverJAsh/Development/frontend/node_modules/jspm/node_modules/uglify-js/lib/parse.js:684:41)\n    at token_error (/Users/OliverJAsh/Development/frontend/node_modules/jspm/node_modules/uglify-js/lib/parse.js:688:9)\n    at unexpected (/Users/OliverJAsh/Development/frontend/node_modules/jspm/node_modules/uglify-js/lib/parse.js:694:9)\n    at expr_atom (/Users/OliverJAsh/Development/frontend/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1189:13)\n    at maybe_unary (/Users/OliverJAsh/Development/frontend/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1363:19)\n    at expr_ops (/Users/OliverJAsh/Development/frontend/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1398:24)\n    at maybe_conditional (/Users/OliverJAsh/Development/frontend/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1403:20)\n    at maybe_assign (/Users/OliverJAsh/Development/frontend/node_modules/jspm/node_modules/uglify-js/lib/parse.js:1427:20)' }
```

If I only bundle `raven` once, the error does not occur. It appears to be something to do with uglify.

**Comment by guybedford** [comment] 2015-06-05 10:19
Do you get identical outputs with minification disabled? Sounds like a strange mutability bug if so.

**Comment by OliverJAsh** [comment] 2015-06-08 10:22
Without minification:

``` js
// a
"format register";
(function() {
function define(){};  define.amd = {};
(System.register("raven", [], false, function() {}));
})();

// b
"format register";
(function() {
function define(){};  define.amd = {};
();
})();
```

**Comment by guybedford** [comment] 2015-06-08 15:19
Thanks it looks like the issue is in that code - 

```javascript
"format register";
(function() {
function define(){};  define.amd = {};
();
})();
```

What did the input source for b look like? It may be some kind of null AMD transformation bug? Are you setting the format to AMD via metadata?

**Comment by OliverJAsh** [comment] 2015-06-08 15:23
The code in my initial post is exactly what is needed to reproduce this.

**Comment by guybedford** [comment] 2015-06-08 15:27
Ok thanks, sounds like mutability then. Will look into replicating and fixing it.

**Comment by guybedford** [comment] 2015-06-15 17:36
@OliverJAsh I think this fits the signature to be caused by https://github.com/systemjs/builder/issues/198. In the mean time I would suggest just running serial builds (with resets). Closing to track on the builder issue.

**Closed by guybedford** 2015-06-15 17:36 UTC
Labels: bug

**Comment by breandr** [comment] 2015-07-06 23:51
I'm also getting JS_Parse_Error when running from commandlie `jspm bundle app/app app-bundle.js --minify`. Works fine without minify, and minify worked prior to updating to latest yesterday. Not sure if same issue?

**Comment by breandr** [comment] 2015-07-07 00:00
Update: My error came from a rogue `let` somewhere that wasn't using 'use strict'. I picked it up when I got an error in the console alerting me to it. I changed it to var and it worked (and I assume if I took the time to set 'use strict' and make sure it worked correctly that would have also resolved the bundling issue)
