### ISSUE TITLE
Jspm addes `jspm:` prefix when installing overrides from command line.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#467] opened 2015-02-02 08:45 UTC
I have this package.json

```
{
  "jspm": {
    "directories": {
      "packages": "party/jspm"
    },
    "configFile": "jspm_config.js",
    "dependencies": {
      "army-knife": "npm:army-knife@^0.2.1",
      "async": "npm:async@^0.9.0",
      "big": "github:MikeMcl/big.js@^2.5.1",
      "bignumber": "github:MikeMcl/bignumber.js@^1.4.1",
      "bootstrap": "^3.2.0",
      "bootstrap-datepicker": "github:eternicode/bootstrap-datepicker@^1.3.0",
      "famous": "github:trusktr/famous@jspm",
      "infamous": "npm:infamous@0.0.37",
      "james-bond": "npm:james-bond@^0.0.0",
      "jquery": "^2.1.1",
      "jquery-tooltipster": "github:iamceege/tooltipster@^3.2.6",
      "jsfromhell": "github:jonasraoni/JSFromHell@master",
      "jss": "npm:jss@^0.10.1",
      "jss-nested": "npm:jss-nested@^0.1.4",
      "leaflet": "github:RickMohr/Leaflet@better-inertial-scrolling",
      "operative": "npm:operative@^0.3.2",
      "string": "npm:string@^3.0.0"
    }
  }
}
```

When I run `jspm install`, nothing is changed. But when I run something like

```
jspm install -y bootstrap@^3.2.0 -o '{ "registry": "jspm", "dependencies": { "jquery": "^2.1.1", "css": "^0.1.0" }, "shim": { "js/bootstrap": { "deps": ["jquery", "../css/bootstrap.min.css!", "../css/bootstrap-theme.min.css!"] }, "css/bootstrap-theme.min.css!": { "deps": ["./bootstrap.min.css!"] } } }'
```

then package.json gets changed to

```
{
  "jspm": {
    "directories": {
      "packages": "party/jspm"
    },
    "configFile": "jspm_config.js",
    "dependencies": {
      "army-knife": "npm:army-knife@^0.2.1",
      "async": "npm:async@^0.9.0",
      "big": "github:MikeMcl/big.js@^2.5.1",
      "bignumber": "github:MikeMcl/bignumber.js@^1.4.1",
      "bootstrap": "jspm:bootstrap@^3.2.0",
      "bootstrap-datepicker": "github:eternicode/bootstrap-datepicker@^1.3.0",
      "bootstrap@^3.2.0": "github:twbs/bootstrap@^3.2.0",
      "famous": "github:trusktr/famous@jspm",
      "infamous": "npm:infamous@0.0.37",
      "james-bond": "npm:james-bond@^0.0.0",
      "jquery": "jspm:jquery@^2.1.1",
      "jquery-tooltipster": "github:iamceege/tooltipster@^3.2.6",
      "jsfromhell": "github:jonasraoni/JSFromHell@master",
      "jss": "npm:jss@^0.10.1",
      "jss-nested": "npm:jss-nested@^0.1.4",
      "leaflet": "github:RickMohr/Leaflet@better-inertial-scrolling",
      "operative": "npm:operative@^0.3.2",
      "string": "npm:string@^3.0.0"
    }
  }
}
```

It now has two bootstraps, one with the jspm: prefix, and jquery now also has the jspm: prefix. Is this supposed to happen?

**Comment by guybedford** [comment] 2015-02-02 09:48
Thanks, yes this is a bug, duplicate of https://github.com/jspm/jspm-cli/issues/466.

**Closed by guybedford** 2015-02-02 09:48 UTC

**Comment by trusktr** [comment] 2015-02-06 07:26
Confirmed, fixed.

**Comment by guybedford** [comment] 2015-02-06 10:18
Thanks.
