### ISSUE TITLE
'configFile' deleted from package.json when installing, uninstalling, or updating packages.

### ISSUE THREAD

**Issue by NoiSek** [jspm/jspm-cli#1296] opened 2015-11-19 19:27 UTC
Possible duplicate of https://github.com/jspm/jspm-cli/issues/196

Using 'jspm install', `jspm update`, or `jspm uninstall` will remove `configFile` from your `package.json`, creating a new `config.js` file at your project root rather than updating the existing one upon running any of those three commands a second time.

Before using `jspm install flux`:

```
"jspm": {
    "configFile": "static/js/config.js",
    "directories": {
      "baseURL": "static/js",
      "packages": "static/js/src"
    },
    "dependencies": {
      "backbone": "npm:backbone@^1.2.3",
      "backbone.babysitter": "npm:backbone.babysitter@^0.1.10",
      "backbone.radio": "npm:backbone.radio@^1.0.2",
      "backbone.wreqr": "github:marionettejs/backbone.wreqr@^1.3.5",
      "backbonereact": "npm:backbone-react-component@^0.10.0",
      "d3": "github:mbostock/d3@^3.5.9",
      "jquery": "github:components/jquery@1.10.2",
      "lodash": "npm:lodash@^3.10.1",
      "marionette": "github:marionettejs/backbone.marionette@^2.4.3",
      "moment": "npm:moment@^2.10.6",
      "radio": "npm:backbone.radio@^1.0.2",
      "react": "npm:react@^0.14.2",
      "react-addons-perf": "npm:react-addons-perf@^0.14.2",
      "react-addons-test-utils": "npm:react-addons-test-utils@^0.14.2",
      "react-dom": "npm:react-dom@^0.14.2",
      "text": "github:systemjs/plugin-text@^0.0.3"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4"
    }
  }
```

After using `jspm install flux`:

```
"jspm": {
    "directories": {
      "baseURL": "static/js",
      "packages": "static/js/src"
    },
    "dependencies": {
      "backbone": "npm:backbone@^1.2.3",
      "backbone.babysitter": "npm:backbone.babysitter@^0.1.10",
      "backbone.radio": "npm:backbone.radio@^1.0.2",
      "backbone.wreqr": "github:marionettejs/backbone.wreqr@^1.3.5",
      "backbonereact": "npm:backbone-react-component@^0.10.0",
      "d3": "github:mbostock/d3@^3.5.9",
      "flux": "npm:flux@^2.1.1",
      "jquery": "github:components/jquery@1.10.2",
      "lodash": "npm:lodash@^3.10.1",
      "marionette": "github:marionettejs/backbone.marionette@^2.4.3",
      "moment": "npm:moment@^2.10.6",
      "radio": "npm:backbone.radio@^1.0.2",
      "react": "npm:react@^0.14.2",
      "react-addons-perf": "npm:react-addons-perf@^0.14.2",
      "react-addons-test-utils": "npm:react-addons-test-utils@^0.14.2",
      "react-dom": "npm:react-dom@^0.14.2",
      "text": "github:systemjs/plugin-text@^0.0.3"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4"
    }
  }
```

**Comment by guybedford** [comment] 2015-11-22 16:46
When config options match defaults, they are removed automatically. This is a duplicate of https://github.com/jspm/jspm-cli/issues/428 and resolved in jspm 0.17 pending the release.

**Closed by guybedford** 2015-11-22 16:46 UTC
