### ISSUE TITLE
Version ranges not supported

### ISSUE THREAD

**Issue by tyrsius** [jspm/jspm-cli#1685] opened 2016-04-05 22:07 UTC
jspm does not seem to respect npm [version ranges](https://docs.npmjs.com/files/package.json#dependencies)

![image](https://cloud.githubusercontent.com/assets/1187432/14299540/e6bbc0d4-fb3f-11e5-829d-87580a62d0e1.png)

![image](https://cloud.githubusercontent.com/assets/1187432/14299533/db6a5cea-fb3f-11e5-9b81-0d0246a5e32e.png)

This should not produce a warning, since the version is already be satisfied. jspm appears to only be looking at the last version in the range.

**Comment by guybedford** [comment] 2016-04-06 11:10
This is a duplicate of https://github.com/jspm/jspm-cli/issues/1253.

**Closed by guybedford** 2016-04-06 11:10 UTC
