### ISSUE TITLE
buffer peer dependency

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#1780] opened 2016-05-04 18:46 UTC
0.17b14...

For some odd reason, buffer keeps moving around causing weird diffs in my package.json... sometimes it is a regular dependency and sometimes it is a peerDep... 

```
-    "peerDependencies": {},
+    "peerDependencies": {
+      "buffer": "github:jspm/nodelibs-buffer@^0.2.0-alpha"
+    },
```

**Comment by guybedford** [comment] 2016-05-05 15:34
Thanks, this sounds like a duplicate of https://github.com/jspm/jspm-cli/issues/1742. I'm looking into it.

**Closed by guybedford** 2016-05-05 15:34 UTC

**Comment by lookfirst** [comment] 2016-05-05 18:15
Yup, looks just like the same issue.
