### ISSUE TITLE
Errors with both babel and traceur loaders in handling my ES6 entrypoint.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#887] opened 2015-06-27 05:19 UTC
Hi @guybedford, I'm trying out 0.15.7. I have this HTML file:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title><%= title %></title>
        <meta charset="utf8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </head>
    <body>
        <script src='/party/jspm/system.src.js'></script>
        <script src='jspm_config.js'></script>
        <script>
            System.paths['js/*'] = 'javascripts/*/main.js';
            System.import('js/home');
        </script>
    </body>
</html>
```

where

```
    "directories": {
      "packages": "party/jspm"
    },
    "configFile": "jspm_config.js",
```

and `javascripts/home/main.js` contains

```
console.log( 'huh?!?!')
```

but I don't see `huh?!?!` logged to the console. It never loads the file. What has changed since v0.11.x? (http://keepachangelog.com)

**Comment by trusktr** [comment] 2015-06-27 23:25
Nevermind, that `console.log('huh?!?!')` works, but if I change the file back to its original content, then nothing happens. The original file looks like this: http://hastebin.com/iqehutoxiz.js

In that case (I'm absolutely positive) then nothing happens. The `console.log('huh?!?!')` never fires, and there are no errors outputted anywhere.

**Comment by trusktr** [comment] 2015-06-27 23:37
I made a video to illustrate what happens: http://youtu.be/mQzrx_6dlx0

**Comment by trusktr** [comment] 2015-06-28 00:39
Alright, running `jspm dl-loader babel` got me further. Now the borwser is loading a bunch of files (I guess babel stuff, es6 stuff, etc) but it never loads jquery, which is the first import in my main.js file, so it messes up before getting to that point I guess.

Here's two screen shots:

![screen shot 2015-06-27 at 5 34 34 pm](https://cloud.githubusercontent.com/assets/297678/8394581/6b15ccac-1cf3-11e5-9e87-1935a25e627c.png)

![screen shot 2015-06-27 at 5 35 40 pm](https://cloud.githubusercontent.com/assets/297678/8394582/6d9029c8-1cf3-11e5-834a-24f0a5410f72.png)

**Comment by trusktr** [comment] 2015-06-28 00:42
When I switch back to `jspm dl-loader --traceur` the browser only loads 10 files instead of a ton:

![screen shot 2015-06-27 at 5 40 59 pm](https://cloud.githubusercontent.com/assets/297678/8394586/c44d160e-1cf3-11e5-8fd4-e304d58311ba.png)


main.js was retrieved, but apparently there's never an attempt to load it? Maybe error handling isn't working so we can see errors? The console is completely empty when using traceur.

**Comment by trusktr** [comment] 2015-06-28 00:44
Maybe this is the problem: 
![screen shot 2015-06-27 at 5 44 10 pm](https://cloud.githubusercontent.com/assets/297678/8394589/256749be-1cf4-11e5-95fb-7274f65bdb1c.png)

**Comment by trusktr** [comment] 2015-06-28 00:48
In both cases (babel and traceur), when my entrypoint has only the single console.log line it works just fine.

**Comment by trusktr** [comment] 2015-06-28 01:02
I don't think this output is related, but just in case:

```
     The following existing package versions were altered by install deduping:

       commander 2.5.1 -> 2.5.0

     To keep existing dependencies locked during install, use the --lock option.

     The following new package versions were substituted by install deduping:

       css 2.2.1 -> 2.1.0

     Installed Forks

                                       npm:commander 2.5.0 2.8.1
                                      npm:esprima-fb 8001.1001.0-dev-harmony-fb 13001.1.0-dev-harmony-fb 14001.1.0-dev-harmony-fb
                                             npm:jss 0.10.2 1.0.8
                                       npm:minimatch 1.0.0 2.0.8
                                        npm:minimist 0.0.8 1.1.1
                                         npm:process 0.10.1 0.11.1
                                      npm:source-map 0.1.32 0.1.43 0.4.2

     To inspect individual package constraints, use jspm inspect registry:name.
```

**Comment by trusktr** [comment] 2015-06-28 01:21
Is this the problem? https://github.com/jspm/jspm-cli/issues/871

The files in readable-stream are requiring files including the `.js` extension.

**Comment by trusktr** [comment] 2015-06-28 01:35
Alright, in the traceur case, changing my entry point to use CommonJS `require` causes required files to be fetched, but they still never get loaded. They never appear in the Sources tab of Chrome Inspector.

Note, I'm still on `0.15.7`.

**Comment by guybedford** [comment] 2015-06-28 18:30
I guess the place to start here is in what is loading `_stream_readable.js.js`. Do you know which of your npm dependencies this might be? Then it could probably be fixed via an override.

Debugging steps:
1. Remove all imports of external packages, and verify loading works of the main file
2. Gradually add back imports until you hit the stream error, working out which import did it.
3. Having determined the module causing the error it should be possible to share a reproducible test case - that `jspm install npm:x..` when import gives the same error.

With the above isolated case, I can fix it for you. But I can't help isolating unfortunately.

Making the above debugging easier is certainly a priority and issue being tracked in the module loader as well.

**Comment by trusktr** [comment] 2015-06-29 23:41
@guybedford I don't think it matters what's loading `_stream_readable.js.js`. I thought you fixed the `require('some-file.js')` (with the `.js` extension) problem a while back?

**Comment by trusktr** [comment] 2015-06-29 23:46
This is the package with the `.js` requires: https://github.com/nodejs/readable-stream/blob/master/passthrough.js

**Comment by guybedford** [comment] 2015-06-30 13:20
@trusktr to explain here, we remove the js requires during processing of npm packages. We do this by seeing that the package requires a file with a .js extension, and remove it as the module loader always adds js extensions itself - `require('x.js') -> require('x')`.

The issue you're having is that something is doing `require('stream/_stream_readable.js`)` I believe, but where `stream` is the external package. This needs to be fixed via an override because during the build analysis we don't have access to the `stream` package to know to do the removal analysis.

The long-term fix is exactly the upgrade that is coming in SystemJS 0.18 and jspm 0.17. That is extensions are treated as optional.

**Comment by trusktr** [comment] 2015-07-01 20:41
@guybedford 

> The long-term fix is exactly the upgrade that is coming in SystemJS 0.18 and jspm 0.17. That is extensions are treated as optional.

Awesome! That will fix lots of things!

**Closed** 2015-07-15 16:28 UTC

**Comment by trusktr** [comment] 2015-09-24 22:33
@guybedford ETA for jspm 0.17? Will it have the following?

* Npm auth disabled by default
* Use github repos instead of release archives be default
* And hence don't use GitHub API by default, just cloning of repos so that user never have to configure any endpoints and usage limits will never apply

**Comment by guybedford** [comment] 2015-09-25 13:42
@trusktr I have a no ETAs policy :) Soon? Registry updates will be prioritised only after 0.17 though.
