### ISSUE TITLE
Keep getting error Registry endpoint processPackage of npm:reflect-metadata@0.1.3 did not return package config. did not return package config.

### ISSUE THREAD

**Issue by el-davo** [jspm/jspm-cli#2004] opened 2016-07-27 07:16 UTC
Hi. I just did a fresh install of jspm

```
jspm install -g jspm@beta
```

My jspm config is this

```
"jspm": {
    "format": "es6",
    "dependencies": {
      "@angular/router-deprecated": "npm:@angular/router-deprecated@2.0.0-rc.1",
      "@angular/upgrade": "npm:@angular/upgrade@2.0.0-rc.1",
      "@angular2-material/button": "npm:@angular2-material/button@2.0.0-alpha.5-2",
      "@angular2-material/icon": "npm:@angular2-material/icon@2.0.0-alpha.5-2",
      "@angular2-material/input": "npm:@angular2-material/input@2.0.0-alpha.5-2",
      "@angular2-material/list": "npm:@angular2-material/list@2.0.0-alpha.5-2",
      "@angular2-material/progress-bar": "npm:@angular2-material/progress-bar@2.0.0-alpha.5-2",
      "@angular2-material/progress-circle": "npm:@angular2-material/progress-circle@2.0.0-alpha.5-2",
      "@angular2-material/sidenav": "npm:@angular2-material/sidenav@2.0.0-alpha.5-2",
      "@angular2-material/toolbar": "npm:@angular2-material/toolbar@2.0.0-alpha.5-2",
      "angular2-fontawesome": "npm:angular2-fontawesome@0.4.0",
      "angular2-localstorage": "npm:angular2-localstorage@^0.4.0",
      "chart.js": "npm:chart.js@2.1.6",
      "css": "github:systemjs/plugin-css@^0.1.23",
      "csv-write-stream": "npm:csv-write-stream@2.0.0",
      "dateformat": "npm:dateformat@1.0.12",
      "electron": "github:jaroslavrehorka/electron-jspm@^0.1.7",
      "lodash": "npm:lodash@4.13.1",
      "ng2-charts": "npm:ng2-charts@1.1.0",
      "ng2-material": "npm:ng2-material@0.5.0",
      "ping-lite": "npm:ping-lite@1.0.1",
      "text": "github:systemjs/plugin-text@^0.0.8",
      "traceroute-lite": "npm:traceroute-lite@0.1.0",
      "xlsx": "npm:xlsx@0.8.0"
    },
    "devDependencies": {
      "plugin-typescript": "github:frankwallis/plugin-typescript@^5.0.8",
      "typescript": "npm:typescript@1.6.2"
    },
    "peerDependencies": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.1",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "@angular/http": "npm:@angular/http@2.0.0-rc.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1",
      "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@2.0.0-rc.1",
      "@angular/router": "npm:@angular/router@2.0.0-rc.1",
      "@angular2-material/checkbox": "npm:@angular2-material/checkbox@2.0.0-alpha.5-2",
      "@angular2-material/core": "npm:@angular2-material/core@2.0.0-alpha.5-2",
      "assert": "github:jspm/nodelibs-assert@^0.2.0-alpha",
      "buffer": "github:jspm/nodelibs-buffer@^0.2.0-alpha",
      "child_process": "github:jspm/nodelibs-child_process@^0.2.0-alpha",
      "constants": "github:jspm/nodelibs-constants@0.2.0-alpha",
      "crypto": "github:jspm/nodelibs-crypto@^0.2.0-alpha",
      "es6-promise": "npm:es6-promise@^3.2.1",
      "es6-shim": "npm:es6-shim@0.35.0",
      "events": "github:jspm/nodelibs-events@0.2.0-alpha",
      "fs": "github:jspm/nodelibs-fs@^0.2.0-alpha",
      "http": "github:jspm/nodelibs-http@^0.2.0-alpha",
      "net": "github:jspm/nodelibs-net@^0.2.0-alpha",
      "os": "github:jspm/nodelibs-os@^0.2.0-alpha",
      "path": "github:jspm/nodelibs-path@^0.2.0-alpha",
      "process": "github:jspm/nodelibs-process@^0.2.0-alpha",
      "reflect-metadata": "npm:reflect-metadata@0.1.3",
      "rxjs": "npm:rxjs@5.0.0-beta.6",
      "stream": "github:jspm/nodelibs-stream@0.2.0-alpha",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.2.0-alpha",
      "tcp-ping": "npm:tcp-ping@^0.1.1",
      "timers": "github:jspm/nodelibs-timers@^0.2.0-alpha",
      "url": "github:jspm/nodelibs-url@0.2.0-alpha",
      "util": "github:jspm/nodelibs-util@0.2.0-alpha",
      "vm": "github:jspm/nodelibs-vm@0.2.0-alpha",
      "zone.js": "npm:zone.js@^0.6.6"
    },
    "overrides": {
      "npm:@angular/common@2.0.0-rc.1": {
        "meta": {
          "src/*.js": {
            "deps": [
              "reflect-metadata",
              "zone.js"
            ]
          }
        }
      },
      "npm:@angular/compiler@2.0.0-rc.1": {
        "meta": {
          "src/*.js": {
            "deps": [
              "reflect-metadata",
              "zone.js"
            ]
          }
        }
      },
      "npm:@angular/core@2.0.0-rc.1": {
        "meta": {
          "src/*.js": {
            "deps": [
              "reflect-metadata",
              "zone.js"
            ]
          }
        }
      },
      "npm:@angular/http@2.0.0-rc.1": {
        "meta": {
          "src/*.js": {
            "deps": [
              "reflect-metadata",
              "zone.js"
            ]
          }
        }
      },
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1": {
        "meta": {
          "src/*.js": {
            "deps": [
              "reflect-metadata",
              "zone.js"
            ]
          }
        }
      },
      "npm:@angular/platform-browser@2.0.0-rc.1": {
        "meta": {
          "src/*.js": {
            "deps": [
              "reflect-metadata",
              "zone.js"
            ]
          }
        }
      },
      "npm:@angular/router@2.0.0-rc.1": {
        "meta": {
          "src/*.js": {
            "deps": [
              "reflect-metadata",
              "zone.js"
            ]
          }
        }
      },
      "npm:font-awesome@4.6.3": {
        "main": "css/font-awesome.css!",
        "jspmNodeConversion": false,
        "registry": "jspm",
        "dependencies": {
          "css": "0.1"
        }
      },
      "npm:inherits@2.0.1": {
        "ignore": [
          "test.js"
        ]
      },
      "npm:lodash@4.13.1": {
        "map": {
          "buffer": "@empty",
          "process": "@empty"
        }
      },
      "npm:moment@2.14.1": {
        "jspmNodeConversion": false
      },
      "npm:readable-stream@1.0.34": {
        "map": {
          "stream": "stream-browserify/index"
        },
        "systemjs": {
          "main": "readable.js"
        },
        "dependencies": {
          "core-util-is": "~1.0.0",
          "isarray": "0.0.1",
          "string_decoder": "~0.10.0",
          "inherits": "~2.0.1",
          "stream-browserify": "~1.0.0"
        }
      },
      "npm:reflect-metadata@0.1.3": {
        "jspmNodeConversion": false,
        "map": {
          "crypto": {
            "node": "@node/crypto",
            "default": "@empty"
          }
        }
      },
      "npm:typescript@1.8.10": {
        "browser": {},
        "map": {
          "buffer": "@empty",
          "child_process": "@empty",
          "fs": "@empty",
          "path": "@empty",
          "process": "@empty",
          "readline": "@empty"
        }
      },
      "npm:typescript@2.0.0": {
        "browser": {},
        "map": {
          "buffer": "@empty",
          "child_process": "@empty",
          "fs": "@empty",
          "path": "@empty",
          "process": "@empty",
          "readline": "@empty"
        }
      }
    }
  }
```

Whenever i do a jspm install i get this error

```shell
err  Error: Registry endpoint processPackage of npm:reflect-metadata@0.1.3 did not return package config.
    at C:\Program Files\nodejs\node_modules\jspm\lib\package.js:871:17
    at tryCatcher (C:\Program Files\nodejs\node_modules\jspm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\jspm\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Program Files\nodejs\node_modules\jspm\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\jspm\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Program Files\nodejs\node_modules\jspm\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Program Files\nodejs\node_modules\jspm\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Program Files\nodejs\node_modules\jspm\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\jspm\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

warn Installation changes not saved.
```

This doesnt happen on every machine but it is happening on 2 out of 3 windows machines for me now and i cant fix it. Any help greatly appreciated?

**Comment by guybedford** [comment] 2016-07-27 12:07
This may be a regression due to the handling of custom npm scope authentication. There's a fix in https://github.com/jspm/npm/pull/146 which may help I think. //cc @glen-84

**Comment by glen-84** [comment] 2016-07-27 12:30
I just tried this with `0.17.0-beta.24`, and I got `ok   Install complete.`.

Maybe he should try clearing cache?

If this is somehow my fault, then I sincerely apologize. :worried:

**Comment by el-davo** [comment] 2016-07-27 12:33
Hi guys

I also have 0.17.0-beta.24 and get same error. Have tried jspm cache-clear command and still same issue. Also tried uninstall jspm with 

npm uninstall jspm -g

and reinstalling, However I get the same issue :(

**Comment by glen-84** [comment] 2016-07-27 12:37
@el-davo Does it work with beta 22?

**Comment by el-davo** [comment] 2016-07-27 12:44
@glen-84 Interestingly the one machine where it does work is on 0.17.0-beta.22. I tried downgrading one the other 2 machines but still i get the same error. Whatever happened it seems to have destroyed my whole setup :laughing: . Ill try and investigate a bit further

**Comment by glen-84** [comment] 2016-07-27 12:47
@el-davo Make sure that you also drop the version of `jspm-npm` -- it might be easiest to remove jspm and then install the specific beta version.

**Comment by el-davo** [comment] 2016-07-27 12:47
The weird thing is somethimes it gets past that bit it failed on. and fails further down the line

err  Error: Registry endpoint processPackage of github:jspm/nodelibs-os@0.2.0-alpha did not return package config.

**Comment by glen-84** [comment] 2016-07-27 13:13
@guybedford,

I've tested this 3 times (twice in dev env, once in production), and I'm not able to reproduce the error. Also, judging by the latest error message, this is not specific to the npm registry.

If you find otherwise, please let me know.

**Comment by el-davo** [comment] 2016-07-27 14:39
So i completely uninstalled nodejs. And deleted all npm cache folders that i could find. Then re-installed node and ran

npm install -g jspm@0.17.0-beta.22

And to my shock the problem still persists. Gonna require more investigations i think :sob:

**Comment by guybedford** [comment] 2016-08-01 17:17
Are you still getting this with the beta.25?

**Comment by guybedford** [comment] 2016-08-01 17:17
Can you share the full install log?

**Comment by el-davo** [comment] 2016-08-02 08:43
Hi @guybedford I just tried with beta.25 and still have the same issue. This is the install log

c:\GIT\emc-ping>jspm i

warn Running jspm globally, it is advisable to locally install jspm via npm
     install jspm --save-dev.

warn Registry handler jspm-github provides a build hook, which has been
     deprecated for processPackage.

warn Registry handler jspm-npm provides a build hook, which has been deprecated
     for processPackage.
     Updating registry cache...
     Downloading npm:lodash@4.13.1
     Downloading npm:typescript@1.8.10
     Downloading npm:@angular/common@2.0.0-rc.1
     Downloading npm:@angular/compiler@2.0.0-rc.1
     Downloading npm:@angular/platform-browser@2.0.0-rc.1
     Downloading npm:@angular/core@2.0.0-rc.1
ok   Peer reflect-metadata to npm:reflect-metadata@0.1.3 (0.1.3)
     Downloading npm:ng2-material@0.5.0
     Downloading npm:angular2-fontawesome@0.4.0
     Downloading npm:dateformat@1.0.12
     Downloading npm:ng2-charts@1.1.0
     Downloading npm:zone.js@0.6.12
     Downloading npm:es6-shim@0.35.0
     Downloading npm:es6-promise@3.2.1
     Downloading npm:xlsx@0.8.0
     Downloading npm:chart.js@2.1.6
     Downloading npm:rxjs@5.0.0-beta.6
     Downloading npm:rxjs@5.0.0-beta.0
     Downloading npm:chart.js@2.1.3
     Downloading npm:@angular2-material/core@2.0.0-alpha.5-2
     Downloading npm:@angular/upgrade@2.0.0-rc.1
     Downloading npm:@angular2-material/checkbox@2.0.0-alpha.5-2
     Downloading npm:@angular2-material/toolbar@2.0.0-alpha.5-2
     Downloading npm:@angular2-material/input@2.0.0-alpha.5-2
     Downloading npm:@angular2-material/sidenav@2.0.0-alpha.5-2
     Downloading npm:@angular2-material/icon@2.0.0-alpha.5-2
     Downloading npm:@angular2-material/progress-bar@2.0.0-alpha.5-2
     Downloading npm:@angular2-material/progress-circle@2.0.0-alpha.5-2
     Downloading npm:@angular2-material/button@2.0.0-alpha.5-2
     Downloading npm:@angular2-material/list@2.0.0-alpha.5-2
ok   Installed peer @angular/http to npm:@angular/http@2.0.0-rc.1 (2.0.0-rc.1)
     Downloading npm:@angular/router-deprecated@2.0.0-rc.1
     Downloading npm:font-awesome@4.6.3
     Downloading npm:moment@2.14.1
     Downloading npm:codepage@1.3.8
     Downloading npm:jszip@2.4.0
     Downloading npm:chartjs-color@1.0.22
     Downloading npm:ssf@0.8.2
     Downloading npm:cfb@0.10.3
ok   Peer tcp-ping to npm:tcp-ping@^0.1.1 (0.1.1)
ok   angular2-localstorage to npm:angular2-localstorage@^0.4.0 (0.4.0)
ok   ping-lite to npm:ping-lite@1.0.1 (1.0.1)
ok   traceroute-lite to npm:traceroute-lite@0.1.0 (0.1.0)
     Downloading npm:argparse@1.0.7
     Downloading npm:pako@0.2.9
     Downloading npm:concat-stream@1.5.1
     Downloading npm:voc@0.5.0
     Downloading github:jspm/nodelibs-assert@0.2.0-alpha
     Downloading npm:frac@0.3.1
     Downloading npm:chartjs-color-string@0.4.0
     Downloading npm:color-convert@0.5.3
     Downloading npm:colors@0.6.2
     Downloading github:systemjs/plugin-text@0.0.8
     Downloading npm:exit-on-epipe@0.0.1
     Downloading npm:minimist@1.2.0
     Downloading npm:normalize-package-data@2.3.5
     Downloading npm:graceful-readlink@1.0.1
     Downloading npm:loud-rejection@1.6.0
     Downloading npm:map-obj@1.0.1
     Downloading npm:object-assign@4.1.0
     Downloading npm:read-pkg-up@1.0.1
     Downloading npm:split2@0.2.1
     Downloading npm:sprintf-js@1.0.3
     Downloading npm:through2@0.6.5
     Downloading npm:is-property@1.0.2
     Downloading npm:readable-stream@2.0.6
     Downloading npm:readable-stream@1.0.34
     Downloading npm:inherits@2.0.1
     Downloading npm:typedarray@0.0.6
     Downloading npm:color-name@1.1.1
     Downloading npm:hosted-git-info@2.1.5
     Downloading npm:validate-npm-package-license@3.0.1
     Downloading npm:semver@5.3.0
     Downloading npm:is-builtin-module@1.0.0
     Downloading npm:find-up@1.1.2
     Downloading npm:read-pkg@1.1.0
     Downloading npm:signal-exit@3.0.0

warn Package npm:dateformat@1.0.12 has no "main" entry point set in its package
     config.
     Downloading npm:camelcase@2.1.1
     Downloading github:jspm/nodelibs-stream@0.2.0-alpha
     Downloading npm:xtend@4.0.1
     Downloading npm:strip-indent@1.0.1
     Downloading npm:indent-string@2.1.0
     Downloading npm:process-nextick-args@1.0.7
     Downloading npm:stream-browserify@1.0.0
     Downloading npm:isarray@1.0.0
     Downloading npm:isarray@0.0.1
     Downloading npm:util-deprecate@1.0.2
     Downloading npm:string_decoder@0.10.31
     Downloading npm:currently-unhandled@0.4.1
     Downloading npm:core-util-is@1.0.2
     Downloading github:jspm/nodelibs-url@0.2.0-alpha
     Downloading npm:spdx-expression-parse@1.0.2
     Downloading npm:load-json-file@1.1.0
     Downloading npm:spdx-correct@1.0.2
     Downloading npm:path-exists@2.1.0
     Downloading npm:path-type@1.1.0
     Downloading npm:builtin-modules@1.1.1
     Downloading npm:pinkie-promise@2.0.1

warn Package npm:ssf@0.8.2 has no "main" entry point set in its package config.
     Downloading npm:repeating@2.0.1
     Downloading npm:array-find-index@1.0.1
     Downloading npm:stream-browserify@2.0.1

warn Package npm:concat-stream@1.5.1 has no "main" entry point set in its
     package config.
     Downloading npm:readable-stream@2.1.4
     Downloading npm:strip-bom@2.0.0
     Downloading npm:pify@2.3.0
     Downloading npm:parse-json@2.2.0

warn Package npm:chartjs-color@1.0.22 has no "main" entry point set in its
     package config.

warn Package npm:object-assign@4.1.0 has no "main" entry point set in its
     package config.

warn Package npm:read-pkg-up@1.0.1 has no "main" entry point set in its package
     config.
     Downloading npm:spdx-license-ids@1.2.1
     Downloading npm:pinkie@2.0.4

warn Package npm:@angular2-material/checkbox@2.0.0-alpha.5-2 has no "main"
     entry point set in its package config.
     Downloading github:jspm/nodelibs-os@0.2.0-alpha

warn Package npm:map-obj@1.0.1 has no "main" entry point set in its package
     config.
ok   Installed npm:ssf@~0.8.1 (0.8.2)
ok   Installed npm:concat-stream (1.5.1)

warn Package npm:es6-promise@3.2.1 has no "main" entry point set in its package
     config.
     Downloading github:jspm/nodelibs-vm@0.2.0-alpha
     Downloading npm:is-finite@1.0.1

warn Package npm:is-property@1.0.2 has no "main" entry point set in its package
     config.

warn Package npm:@angular2-material/toolbar@2.0.0-alpha.5-2 has no "main" entry
     point set in its package config.

warn Package npm:through2@0.6.5 has no "main" entry point set in its package
     config.

warn Package npm:graceful-readlink@1.0.1 has no "main" entry point set in its
     package config.
     Downloading npm:url@0.11.0
     Downloading npm:buffer-shims@1.0.0

warn Package npm:color-name@1.1.1 has no "main" entry point set in its package
     config.

warn Package npm:@angular2-material/list@2.0.0-alpha.5-2 has no "main" entry
     point set in its package config.

warn Package npm:voc@0.5.0 has no "main" entry point set in its package config.
     Downloading npm:graceful-fs@4.1.4

warn Package npm:@angular2-material/progress-circle@2.0.0-alpha.5-2 has no
     "main" entry point set in its package config.

warn Package npm:cfb@0.10.3 has no "main" entry point set in its package
     config.

warn Package npm:@angular2-material/progress-bar@2.0.0-alpha.5-2 has no "main"
     entry point set in its package config.

warn Package npm:chartjs-color-string@0.4.0 has no "main" entry point set in
     its package config.

warn Package npm:validate-npm-package-license@3.0.1 has no "main" entry point
     set in its package config.
ok   Installed npm:read-pkg-up@^1.0.1 (1.0.1)
ok   Installed npm:object-assign@^4.0.1 (4.1.0)
     Downloading npm:error-ex@1.3.0

warn Package npm:loud-rejection@1.6.0 has no "main" entry point set in its
     package config.

warn Package npm:inherits@2.0.1 has no "main" entry point set in its package
     config.
ok   Installed npm:map-obj@^1.0.1 (1.0.1)
ok   Installed peer @angular2-material/checkbox to
     npm:@angular2-material/checkbox@2.0.0-alpha.5-2 (2.0.0-alpha.5-2)
ok   Installed npm:chartjs-color@^1.0.2 (1.0.22)
     Downloading npm:is-utf8@0.2.1

warn Package npm:is-builtin-module@1.0.0 has no "main" entry point set in its
     package config.

warn Package npm:camelcase@2.1.1 has no "main" entry point set in its package
     config.
ok   Installed npm:spdx-exceptions@^1.0.4 (1.0.5)
ok   Installed npm:is-property@^1.0.0 (1.0.2)
     Downloading github:jspm/nodelibs-crypto@0.2.0-alpha
ok   Installed npm:through2@^0.6.1 (0.6.5)

warn Package npm:find-up@1.1.2 has no "main" entry point set in its package
     config.

warn Package npm:read-pkg@1.1.0 has no "main" entry point set in its package
     config.
ok   Installed npm:graceful-readlink (1.0.1)

warn Package npm:indent-string@2.1.0 has no "main" entry point set in its
     package config.
ok   Installed npm:color-name@^1.0.0 (1.1.1)
ok   Installed npm:voc (0.5.0)
     Downloading npm:punycode@1.3.2
     Downloading npm:querystring@0.2.0
     Downloading npm:os-browserify@0.2.1

warn Package npm:frac@0.3.1 has no "main" entry point set in its package
     config.

err  Error: Registry endpoint processPackage of github:jspm/nodelibs-stream@0.2.
0-alpha did not return package config.
    at C:\Users\ahernd2\AppData\Roaming\npm\node_modules\jspm\lib\package.js:874
:17
    at tryCatcher (C:\Users\ahernd2\AppData\Roaming\npm\node_modules\jspm\node_m
odules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\ahernd2\AppData\Roaming\npm\n
ode_modules\jspm\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\ahernd2\AppData\Roaming\npm\node_modules
\jspm\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\ahernd2\AppData\Roaming\npm\node_module
s\jspm\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\ahernd2\AppData\Roaming\npm\node_module
s\jspm\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Users\ahernd2\AppData\Roaming\npm\node_modules\jspm
\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\ahernd2\AppData\Roaming\npm\node_modules\jsp
m\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\ahernd2\AppData\R
oaming\npm\node_modules\jspm\node_modules\bluebird\js\release\async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

warn Installation changes not saved.

**Comment by el-davo** [comment] 2016-08-02 08:53
Maybe something to do with this warning?

warn Registry handler jspm-github provides a build hook, which has been
     deprecated for processPackage.

@guybedford do you know what that warning means?

**Comment by guybedford** [comment] 2016-08-02 11:50
@el-davo it sounds like you are running the wrong version of jspm-github against the jspm install. Try running `npm install jspm-github` perhaps.

**Comment by el-davo** [comment] 2016-08-02 14:42
Im happy to report its fixed. Im going to speculate what the issue was. Basically I had 2 npm packages i had to uninstall.

npm uninstall jspm-github
npm uninstall npm-github

Am not sure what those packages were doing there. I guess maybe from an older version of jspm. However with those 2 packages gone it seems to work.

**Comment by phoeniceus** [comment] 2016-08-04 15:44
I had this problem too and after reading this thread, I figured the problem was because I had not sufficiently removed a previous version of jspm. I solved it by:

1. Deleting my node_modules and jspm_packages folders (but kept jspm.config.js)
2. npm uninstall -g jspm
3. npm uninstall jspm
4. npm install -g jspm
5. npm install jspm --save-dev
6. jspm init
7. jspm install

**Comment by guybedford** [comment] 2016-08-05 12:40
I've added https://github.com/jspm/jspm-cli/commit/d497fcff314044a026e8781c200b03a6cdbe64c6 for the beta version of jspm which should fix the confusion here where local jspm-github or jspm-npm versions could interfere with the running of jspm 0.17.

**Comment by guybedford** [comment] 2016-08-21 18:19
This should be fixed in the latest release.

**Closed by guybedford** 2016-08-21 18:19 UTC
Labels: fixed pending release
