### ISSUE TITLE
jspm install changing peer dependency version of react when running on a different machine.

### ISSUE THREAD

**Issue by jithin1987** [jspm/jspm-cli#2027] opened 2016-08-12 23:47 UTC
I have this situation. My existing `package.json` & `jspm.config.js` have react peer dependency  as `"npm:react@^15.3.0"` but running `jspm install` in a different machine changes react version to `0.14.8`

I do recall that on the machine where I first did the set up, it asked me to select  react version, and I chose `0.15` ? So shouldn't it be fixed to `0.15` where ever I run `jspm install`

What could be causing this ?

**Comment by jithin1987** [comment] 2016-08-13 00:02
Also another observation. I ran `jspm install npm:react@~0.14 --peer` on one machine which updated peerDependencies section to have this - `"react": "npm:react@~0.14",`

However `jspm install` on another machine changed this to `"react": "npm:react@^0.14.8",`

**Comment by jithin1987** [comment] 2016-08-21 16:38
By changing I meant `jspm install` modified `package.json` & `jspm.config.js` when running on a different machine.

**Comment by laurentgoudet** [comment] 2016-10-14 07:49
I can confirm this looks like a bug, I am seeing the same thing with Angular 2 peer dependencies.

**Comment by jithin1987** [comment] 2016-10-17 23:15
I am seeing this behavior again.

I did `jspm install npm:react@15.3.2  --peer` on one machine. That updated `package.json` to have an entry like this `react: npm:react@15.3.2,`
Then another machine which did `jspm install` modified it to `react: npm:react@^15.3.2,`

My build system catch modifications to local git checkout and aborts build if it detects one. JSPM modifying `package.json` is a problem.

I am on 0.17.0-beta.28

**Comment by guybedford** [comment] 2016-10-19 13:19
This does sound like a bug as `jspm install` should respect the set value.

**Comment by mikz** [comment] 2016-11-14 20:36
I'm having issue just with plain `jspm install` of already locked dependencies.

Here are two runs on the same machine:

```
     Updating registry cache...
ok   Installed peer moment to npm:moment@^2.10.3 (2.15.0)
ok   Installed npm:d3@~3.5.0 (3.5.17)
ok   Installed peer jquery to github:components/jquery@^2.1.4 (2.1.4)
ok   Installed npm:jquery (github:components/jquery@2.1.4)
ok   Installed npm:moment (2.15.0)
ok   Installed dev dependency constants to npm:jspm-nodelibs-constants@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-buffer@^0.2.0 (0.2.0)
ok   Installed peer process to npm:jspm-nodelibs-process@0.2.0 (0.2.0)
ok   Installed dev dependency vm to npm:jspm-nodelibs-vm@^0.2.0 (0.2.0)
ok   Installed classnames to npm:classnames@^2.2.5 (2.2.5)
ok   Installed peer assert to npm:jspm-nodelibs-assert@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-http@^0.2.0 (0.2.0)
ok   Installed peer fs to npm:jspm-nodelibs-fs@^0.2.0 (0.2.0)
ok   Installed dev dependency net to npm:jspm-nodelibs-net@^0.2.0 (0.2.0)
ok   Installed peer pluralize to npm:pluralize@^1.1.2 (1.2.1)
ok   Installed peer path to npm:jspm-nodelibs-path@^0.2.0 (0.2.0)
ok   Installed dev dependency module to npm:jspm-nodelibs-module@^0.2.0 (0.2.0)
ok   Installed dev dependency tty to npm:jspm-nodelibs-tty@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-url@^0.2.0 (0.2.0)
ok   Installed dev dependency child_process to npm:jspm-nodelibs-child_process@^0.2.0 (0.2.0)
ok   Installed dev dependency util to npm:jspm-nodelibs-util@^0.2.0 (0.2.0)
ok   Installed dev dependency events to npm:jspm-nodelibs-events@^0.2.0 (0.2.0)
ok   Installed dev dependency tls to npm:jspm-nodelibs-tls@^0.2.0 (0.2.0)
ok   Installed dev dependency https to npm:jspm-nodelibs-https@^0.2.0 (0.2.1)
ok   Installed dev dependency npm:jspm-nodelibs-os@^0.2.0 (0.2.0)
ok   Installed moment-range to npm:moment-range@^2.2.0 (2.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-crypto@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-stream@^0.2.0 (0.2.0)
ok   Installed peer fetch to github:github/fetch@^0.9.0 (0.9.0)
ok   Installed peer highcharts to github:highcharts/highcharts-dist@^4.2.1 (4.2.1)
ok   Installed highcharts-export-csv to npm:highcharts-export-csv@^1.3.8 (1.3.8)
ok   Installed plugin-babel to npm:systemjs-plugin-babel@^0.0.17 (0.0.17)
ok   Installed npm:regenerator-runtime@^0.9.5 (0.9.6)
ok   Installed dev dependency npm:url@^0.11.0 (0.11.0)
ok   Installed dev dependency npm:string_decoder@^0.10.31 (0.10.31)
ok   Installed dev dependency string_decoder to npm:jspm-nodelibs-string_decoder@^0.2.0 (0.2.0)
ok   Installed npm:global@^4.3.0 (4.3.0)
ok   Installed npm:simpler-debounce@1.0.0 (1.0.0)
ok   Installed dev dependency npm:commander@2.8 (2.8.1)
ok   Installed npm:error@^4.3.0 (4.4.0)
ok   Installed npm:ev-store@^7.0.0 (7.0.0)
ok   Installed dev dependency npm:os-browserify@^0.2.0 (0.2.0)
ok   Installed npm:virtual-dom@2.1.1 (2.1.1)
ok   Installed decca to npm:decca@^2.1.0 (2.2.2)
ok   Installed numeral to npm:numeral@^1.5.3 (1.5.3)
ok   Installed dev dependency npm:stream-browserify@^2.0.1 (2.0.1)
ok   Installed dev dependency npm:babel-plugin-syntax-jsx@^6.8.0 (6.18.0)
ok   Installed dev dependency npm:babel-plugin-syntax-object-rest-spread@^6.8.0 (6.13.0)
ok   Installed dev dependency npm:babel-helper-builder-react-jsx@^6.8.0 (6.18.0)
ok   Installed npm:is-object@^1.0.1 (1.0.1)
ok   Installed npm:next-tick@^0.2.2 (0.2.2)
ok   Installed npm:browser-split@0.0.1 (0.0.1)
ok   Installed npm:x-is-string@0.1.0 (0.1.0)
ok   Installed npm:x-is-array@0.1.0 (0.1.0)
ok   Installed moment-timezone to npm:moment-timezone@^0.5.5 (0.5.5)
ok   Installed dev dependency npm:browserify-zlib@^0.1.4 (0.1.4)
ok   Installed dev dependency npm:crypto-browserify@^3.11.0 (3.11.0)
ok   Installed dev dependency npm:buffer@^4.0.0 (4.7.1)
ok   Installed dev dependency npm:source-map@0.4 (0.4.4)
ok   Installed dev dependency npm:string_decoder@0.10 (0.10.31)
ok   Installed dev dependency npm:stream-http@^2.0.2 (2.3.0)
ok   Installed dev dependency npm:isarray@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:isarray@1.0 (1.0.0)
ok   Installed dev dependency npm:browserify-cipher@^1.0.0 (1.0.0)
ok   Installed npm:individual@^3.0.0 (3.0.0)
ok   Installed dev dependency npm:builtin-status-codes@^2.0.0 (2.0.0)
ok   Installed dev dependency npm:inherits@~2.0.1 (2.0.1)
ok   Installed dev dependency npm:inherits@^2.0.1 (2.0.1)
ok   Installed dev dependency npm:create-hash@^1.1.0 (1.1.2)
ok   Installed dev dependency npm:create-hmac@^1.1.0 (1.1.4)
ok   Installed dev dependency npm:create-ecdh@^4.0.0 (4.0.0)
ok   Installed dev dependency npm:amdefine (1.0.0)
ok   Installed dev dependency npm:randombytes@^2.0.0 (2.0.3)
ok   Installed npm:process@~0.5.1 (0.5.2)
ok   Installed dev dependency npm:punycode@1.3.2 (1.3.2)
ok   Installed dev dependency npm:graceful-readlink (1.0.1)
ok   Installed dev dependency clean-css to npm:clean-css@^3.4.10 (3.4.10)
ok   Installed npm:string-template@0.2 (0.2.1)
ok   Installed dev dependency npm:browserify-sign@^4.0.0 (4.0.0)
ok   Installed dev dependency npm:ieee754@^1.1.4 (1.1.6)
ok   Installed dev dependency npm:base64-js@^1.0.2 (1.1.2)
ok   Installed dev dependency npm:to-arraybuffer@^1.0.0 (1.0.1)
ok   Installed dev dependency npm:xtend@^4.0.0 (4.0.1)
ok   Installed npm:xtend@4.0 (4.0.1)
ok   Installed dev dependency npm:pbkdf2@^3.0.3 (3.0.4)
ok   Installed dev dependency npm:diffie-hellman@^5.0.0 (5.0.2)
ok   Installed plugin-css to github:systemjs/plugin-css@^0.1.32 (0.1.32)
ok   Installed github:systemjs/plugin-css@^0.1.0 (0.1.32)
ok   Installed c3 to npm:c3@^0.4.11 (0.4.11)
ok   Installed npm:camelize@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:esutils@^2.0.0 (2.0.2)
ok   Installed dev dependency npm:querystring@0.2.0 (0.2.0)
ok   Installed dev dependency npm:babel-runtime@^6.0.0 (6.18.0)
ok   Installed dev dependency transform-object-rest-spread to npm:babel-plugin-transform-object-rest-spread@^6.3.13 (6.16.0)
ok   Installed npm:babel-runtime@^6.9.0 (6.18.0)
ok   Installed transform-runtime to npm:babel-plugin-transform-runtime@^6.9.0 (6.15.0)
ok   Installed dev dependency npm:public-encrypt@^4.0.0 (4.0.0)
ok   Installed dev dependency npm:readable-stream@^2.0.2 (2.1.4)
ok   Installed dev dependency npm:readable-stream@^2.1.0 (2.1.4)
ok   Installed dev dependency npm:babel-types@^6.18.0 (6.18.0)
ok   Installed dev dependency npm:pako@0.2 (0.2.8)
ok   Installed npm:min-document@^2.6.1 (2.18.0)
ok   Installed npm:jquery@^2.2.0 (2.2.1)
ok   Installed select2 to github:select2/select2@^4.0.1 (4.0.1)
ok   Installed dev dependency npm:evp_bytestokey@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:browserify-des@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:process-nextick-args@~1.0.6 (1.0.7)
ok   Installed dev dependency npm:buffer-shims@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:util-deprecate@~1.0.1 (1.0.2)
ok   Installed dev dependency npm:cipher-base@^1.0.1 (1.0.2)
ok   Installed dev dependency npm:to-fast-properties@^1.0.1 (1.0.2)
ok   Installed dev dependency npm:browserify-rsa@^4.0.0 (4.0.1)
ok   Installed dev dependency npm:ripemd160@^1.0.0 (1.0.1)
ok   Installed dev dependency npm:core-util-is@1.0 (1.0.2)
ok   Installed dev dependency zlib to npm:jspm-nodelibs-zlib@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:browserify-aes@^1.0.4 (1.0.6)
ok   Installed dev dependency npm:miller-rabin@^4.0.0 (4.0.0)
ok   Installed dev dependency npm:sha.js@^2.3.6 (2.4.5)
ok   Installed dev dependency npm:bn.js@^4.1.0 (4.11.3)
ok   Installed dev dependency npm:parse-asn1@^5.0.0 (5.0.0)
ok   Installed npm:dom-walk@^0.1.0 (0.1.1)
ok   Installed peer virtual-dom to npm:virtual-dom@^2.1.1 (2.1.1)
ok   Installed dev dependency npm:elliptic@^6.0.0 (6.2.3)
ok   Installed dev dependency npm:buffer-xor@^1.0.2 (1.0.3)
ok   Installed dev dependency npm:brorand@^1.0.1 (1.0.5)
ok   Installed dev dependency npm:des.js@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:hash.js@^1.0.0 (1.0.3)
ok   Installed dev dependency npm:asn1.js@^4.0.0 (4.6.0)
ok   Installed dev dependency npm:minimalistic-assert@^1.0.0 (1.0.0)
ok   Installed peer jquery-ui to github:components/jqueryui@^1.11.4 (1.11.4)
ok   Installed dev dependency npm:lodash@^4.2.0 (4.17.0)
ok   Installed dev dependency transform-react-jsx to npm:babel-plugin-transform-react-jsx@^6.4.0 (6.8.0)
ok   Installed dev dependency core-js to npm:core-js@^1.1.4 (2.4.1)
ok   Installed npm:core-js@^2.4.0 (2.4.1)
ok   Installed babel-runtime to npm:babel-runtime@^6.6.1 (6.18.0)
     Removing package files for github:jspm/nodelibs-process@0.2.0-alpha
     Install tree has no forks.
     Install tree has no forks.
```

```
     Updating registry cache...
ok   Installed peer moment to npm:moment@^2.10.3 (2.15.0)
ok   Installed npm:d3@~3.5.0 (3.5.17)
ok   Installed peer jquery to github:components/jquery@^2.1.4 (2.1.4)
ok   Installed npm:jquery (github:components/jquery@2.1.4)
ok   Installed npm:moment (2.15.0)
ok   Installed dev dependency npm:jspm-nodelibs-os@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-http@^0.2.0 (0.2.0)
ok   Installed dev dependency vm to npm:jspm-nodelibs-vm@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-buffer@^0.2.0 (0.2.0)
ok   Installed dev dependency child_process to npm:jspm-nodelibs-child_process@^0.2.0 (0.2.0)
ok   Installed dev dependency module to npm:jspm-nodelibs-module@^0.2.0 (0.2.0)
ok   Installed dev dependency net to npm:jspm-nodelibs-net@^0.2.0 (0.2.0)
ok   Installed dev dependency constants to npm:jspm-nodelibs-constants@^0.2.0 (0.2.0)
ok   Installed dev dependency events to npm:jspm-nodelibs-events@^0.2.0 (0.2.0)
ok   Installed dev dependency tty to npm:jspm-nodelibs-tty@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-util@^0.2.0 (0.2.0)
ok   Installed peer pluralize to npm:pluralize@^1.1.2 (1.2.1)
ok   Installed peer assert to npm:jspm-nodelibs-assert@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-url@^0.2.0 (0.2.0)
ok   Installed classnames to npm:classnames@^2.2.5 (2.2.5)
ok   Installed dev dependency tls to npm:jspm-nodelibs-tls@^0.2.0 (0.2.0)
ok   Installed dev dependency https to npm:jspm-nodelibs-https@^0.2.0 (0.2.1)
ok   Installed peer fs to npm:jspm-nodelibs-fs@^0.2.0 (0.2.0)
ok   Installed peer path to npm:jspm-nodelibs-path@^0.2.0 (0.2.0)
ok   Installed moment-range to npm:moment-range@^2.2.0 (2.2.0)
ok   Installed peer process to npm:jspm-nodelibs-process@0.2.0 (0.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-crypto@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:jspm-nodelibs-stream@^0.2.0 (0.2.0)
ok   Installed plugin-babel to npm:systemjs-plugin-babel@^0.0.17 (0.0.17)
ok   Installed dev dependency npm:os-browserify@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:commander@2.8 (2.8.1)
ok   Installed npm:ev-store@^7.0.0 (7.0.0)
ok   Installed npm:error@^4.3.0 (4.4.0)
ok   Installed npm:regenerator-runtime@^0.9.5 (0.9.6)
ok   Installed dev dependency npm:string_decoder@^0.10.31 (0.10.31)
ok   Installed dev dependency string_decoder to npm:jspm-nodelibs-string_decoder@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:url@^0.11.0 (0.11.0)
ok   Installed npm:simpler-debounce@1.0.0 (1.0.0)
ok   Installed npm:global@^4.3.0 (4.3.0)
ok   Installed peer fetch to github:github/fetch@^0.9.0 (0.9.0)
ok   Installed npm:virtual-dom@2.1.1 (2.1.1)
ok   Installed decca to npm:decca@^2.1.0 (2.2.2)
ok   Installed numeral to npm:numeral@^1.5.3 (1.5.3)
ok   Installed dev dependency npm:babel-plugin-syntax-jsx@^6.8.0 (6.18.0)
ok   Installed dev dependency npm:babel-helper-builder-react-jsx@^6.8.0 (6.18.0)
ok   Installed npm:x-is-array@0.1.0 (0.1.0)
ok   Installed npm:browser-split@0.0.1 (0.0.1)
ok   Installed npm:next-tick@^0.2.2 (0.2.2)
ok   Installed npm:x-is-string@0.1.0 (0.1.0)
ok   Installed npm:is-object@^1.0.1 (1.0.1)
ok   Installed dev dependency npm:stream-browserify@^2.0.1 (2.0.1)
ok   Installed dev dependency npm:babel-plugin-syntax-object-rest-spread@^6.8.0 (6.13.0)
ok   Installed peer highcharts to github:highcharts/highcharts-dist@^4.2.1 (4.2.1)
ok   Installed highcharts-export-csv to npm:highcharts-export-csv@^1.3.8 (1.3.8)
ok   Installed moment-timezone to npm:moment-timezone@^0.5.5 (0.5.5)
ok   Installed dev dependency npm:source-map@0.4 (0.4.4)
ok   Installed dev dependency npm:browserify-zlib@^0.1.4 (0.1.4)
ok   Installed dev dependency npm:crypto-browserify@^3.11.0 (3.11.0)
ok   Installed dev dependency npm:string_decoder@0.10 (0.10.31)
ok   Installed peer process to github:jspm/nodelibs-process@^0.2.0-alpha (0.2.0-alpha)
ok   Installed dev dependency npm:buffer@^4.0.0 (4.7.1)
ok   Installed dev dependency npm:stream-http@^2.0.2 (2.3.0)
ok   Installed dev dependency npm:inherits@^2.0.1 (2.0.1)
ok   Installed dev dependency npm:inherits@~2.0.1 (2.0.1)
ok   Installed dev dependency npm:xtend@^4.0.0 (4.0.1)
ok   Installed npm:xtend@4.0 (4.0.1)
ok   Installed dev dependency npm:to-arraybuffer@^1.0.0 (1.0.1)
ok   Installed dev dependency npm:graceful-readlink (1.0.1)
ok   Installed dev dependency npm:builtin-status-codes@^2.0.0 (2.0.0)
ok   Installed dev dependency npm:browserify-sign@^4.0.0 (4.0.0)
ok   Installed dev dependency npm:amdefine (1.0.0)
ok   Installed dev dependency npm:create-ecdh@^4.0.0 (4.0.0)
ok   Installed dev dependency npm:isarray@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:isarray@1.0 (1.0.0)
ok   Installed dev dependency npm:create-hash@^1.1.0 (1.1.2)
ok   Installed dev dependency npm:create-hmac@^1.1.0 (1.1.4)
ok   Installed dev dependency npm:randombytes@^2.0.0 (2.0.3)
ok   Installed dev dependency npm:browserify-cipher@^1.0.0 (1.0.0)
ok   Installed npm:individual@^3.0.0 (3.0.0)
ok   Installed npm:process@~0.5.1 (0.5.2)
ok   Installed dev dependency npm:punycode@1.3.2 (1.3.2)
ok   Installed npm:string-template@0.2 (0.2.1)
ok   Installed dev dependency npm:ieee754@^1.1.4 (1.1.6)
ok   Installed dev dependency npm:base64-js@^1.0.2 (1.1.2)
ok   Installed dev dependency npm:esutils@^2.0.0 (2.0.2)
ok   Installed npm:camelize@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:pbkdf2@^3.0.3 (3.0.4)
ok   Installed dev dependency npm:diffie-hellman@^5.0.0 (5.0.2)
ok   Installed dev dependency npm:querystring@0.2.0 (0.2.0)
ok   Installed dev dependency clean-css to npm:clean-css@^3.4.10 (3.4.10)
ok   Installed dev dependency npm:public-encrypt@^4.0.0 (4.0.0)
ok   Installed dev dependency npm:readable-stream@^2.1.0 (2.1.4)
ok   Installed dev dependency npm:readable-stream@^2.0.2 (2.1.4)
ok   Installed peer process to npm:jspm-nodelibs-process@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:pako@0.2 (0.2.8)
ok   Installed dev dependency npm:babel-types@^6.18.0 (6.18.0)
ok   Installed npm:min-document@^2.6.1 (2.18.0)
ok   Installed dev dependency npm:babel-runtime@^6.0.0 (6.18.0)
ok   Installed dev dependency transform-object-rest-spread to npm:babel-plugin-transform-object-rest-spread@^6.3.13 (6.16.0)
ok   Installed npm:babel-runtime@^6.9.0 (6.18.0)
ok   Installed transform-runtime to npm:babel-plugin-transform-runtime@^6.9.0 (6.15.0)
ok   Installed plugin-css to github:systemjs/plugin-css@^0.1.32 (0.1.32)
ok   Installed github:systemjs/plugin-css@^0.1.0 (0.1.32)
ok   Installed c3 to npm:c3@^0.4.11 (0.4.11)
ok   Installed dev dependency npm:buffer-shims@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:process-nextick-args@~1.0.6 (1.0.7)
ok   Installed dev dependency npm:util-deprecate@~1.0.1 (1.0.2)
ok   Installed dev dependency npm:evp_bytestokey@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:cipher-base@^1.0.1 (1.0.2)
ok   Installed dev dependency npm:browserify-rsa@^4.0.0 (4.0.1)
ok   Installed dev dependency npm:to-fast-properties@^1.0.1 (1.0.2)
ok   Installed dev dependency npm:core-util-is@1.0 (1.0.2)
ok   Installed dev dependency zlib to npm:jspm-nodelibs-zlib@^0.2.0 (0.2.0)
ok   Installed dev dependency npm:browserify-des@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:browserify-aes@^1.0.4 (1.0.6)
ok   Installed dev dependency npm:ripemd160@^1.0.0 (1.0.1)
ok   Installed npm:jquery@^2.2.0 (2.2.1)
ok   Installed select2 to github:select2/select2@^4.0.1 (4.0.1)
ok   Installed dev dependency npm:sha.js@^2.3.6 (2.4.5)
ok   Installed dev dependency npm:miller-rabin@^4.0.0 (4.0.0)
ok   Installed npm:dom-walk@^0.1.0 (0.1.1)
ok   Installed peer virtual-dom to npm:virtual-dom@^2.1.1 (2.1.1)
ok   Installed dev dependency npm:bn.js@^4.1.1 (4.11.3)
ok   Installed dev dependency npm:parse-asn1@^5.0.0 (5.0.0)
ok   Installed dev dependency npm:elliptic@^6.0.0 (6.2.3)
ok   Installed dev dependency npm:buffer-xor@^1.0.2 (1.0.3)
ok   Installed dev dependency npm:brorand@^1.0.1 (1.0.5)
ok   Installed dev dependency npm:des.js@^1.0.0 (1.0.0)
ok   Installed dev dependency npm:hash.js@^1.0.0 (1.0.3)
ok   Installed dev dependency npm:asn1.js@^4.0.0 (4.6.0)
ok   Installed dev dependency npm:minimalistic-assert@^1.0.0 (1.0.0)
ok   Installed peer jquery-ui to github:components/jqueryui@^1.11.4 (1.11.4)
ok   Installed dev dependency npm:lodash@^4.2.0 (4.17.0)
ok   Installed dev dependency transform-react-jsx to npm:babel-plugin-transform-react-jsx@^6.4.0 (6.8.0)
ok   Installed dev dependency core-js to npm:core-js@^1.1.4 (2.4.1)
ok   Installed npm:core-js@^2.4.0 (2.4.1)
ok   Installed babel-runtime to npm:babel-runtime@^6.6.1 (6.18.0)
     Removing package files for npm:jspm-nodelibs-process@0.2.0
     Install tree has no forks.

ok   Install complete.
```

Imo it can depend on the order they are processed or something.

**Comment by zenorbi** [comment] 2017-04-12 07:44
@guybedford I probably have a fix for this, however I'm unfamiliar with the codebase and thus not confident enough that this solution would work on other cases. I was able to reproduce peer flickering with a one time `jspm install aurelia-bootstrapper` and many many `jspm install -f --yes` commands. 

Could you please take a look at my code?

https://github.com/zenorbi/jspm-cli/commit/33cad2ef95cd6c691432a5b2a1fc3bb98c62465f

**Comment by guybedford** [comment] 2017-04-12 14:01
@zenorbi that looks really great, would you be able to send a PR? I'd also need to do further testing to be sure. Does the commit resolve the problem for you as far as you can see?

**Comment by zenorbi** [comment] 2017-04-12 14:07
@guybedford PR sent and yes, this seems to resolve the problem, getting both branches fired depending of the order which the dependencies download in and the fix solved the `aurelia-bootstrapper` peer dependency issue. However I'm not really certain if the range to minimum compatible semver conversion is ok, and I'm also not sure if conflicting peer dependencies (^1.0.0 and ^2.0.0) would get handled by the conflict resolution before the pjson update.

**Closed** 2019-04-24 02:20 UTC
Labels: 🐞 bug
