### ISSUE TITLE
0.16.44 Breaks jspm bundleSFX (System is not defined)

### ISSUE THREAD

**Issue by 4storia** [jspm/jspm-cli#2039] opened 2016-08-22 19:30 UTC
In my gulp task to minify my code for deployment, I do the following:

```
var dist = path.join(paths.dist + 'app.js');

return jspm.bundleSFX('app', dist, {
    minify: true,
    mangle: false
})...
```

I get the following error in the browser on load: `app.min.js:166 Uncaught ReferenceError: System is not defined`

A different error is produced on 0.16.43 (which, I would imagine is why 0.16.44 landed so soon after 0.16.43). Switching backing 0.16.42 restores the bundle process back to a working state.
Happy to provide more info if needed.

**Comment by JordanBelford** [comment] 2016-08-24 00:22
@4storia I had the same issue with 0.16.44, and can confirm that 0.16.42 works.

**Comment by guybedford** [comment] 2016-08-24 15:02
Marking as a duplicate of https://github.com/systemjs/builder/issues/673.

**Comment by guybedford** [comment] 2016-08-24 15:49
Fixed released.

**Closed by guybedford** 2016-08-24 15:49 UTC
