### ISSUE TITLE
Bundling does not output correct module order with multiple mains

### ISSUE THREAD

**Issue by lyptt** [jspm/jspm-cli#1285] opened 2015-11-12 18:08 UTC
I've got a slightly convoluted dependency which is a jQuery plugin. The plugin itself has one main file which is correctly imported by JSPM, and two other files which when loaded, patch the main plugin object with extra properties.

When loading via SystemJS in a non-bundled way, everything works fine. My imports look like this:

```
import 'plugin';
import 'plugin/src/pluginFile2';
import 'plugin/src/pluginFile3';
```

This order has to be explicitly followed otherwise the entire script bundle will break due to the plugin erroring.

Is there any way of convincing `jspm bundle` and `jspm bundle-sfx` to load these dependencies in the correct order?

On further investigation into the plugin it seems to not be explicitly requiring the other dependencies, which is probably why JSPM isn't inferring the correct order. Is there any way of shimming this explicitly?

**Comment by guybedford** [comment] 2015-11-15 13:13
@lyptt execution order is not currently guaranteed, although it will be in future as that is currently in the spec.

You need to explicitly set the dependency of `plugin/src/pluginFile2` on `plugin` via a shim or require / import in the plugin itself.

**Comment by lyptt** [comment] 2015-11-15 21:30
@guybedford yeah I thought of this option too, something as trivial as using CommonJS requires in a shim file and tricking whatever's inferring dependencies into thinking they're needed in the order I expect. At the moment I've gone the route of concatting the scripts into one big 'shim' file which I use instead of the original package dependency until this can be resolved properly.

Obviously module dependency ordering is a tricky subject, but it'll probably become increasingly needed in the future especially when depending on an inferred load order provided by JSPM's depcache, which also exhibits broken ordering. That's the sole reason we're not currently making use of SPDY/HTTP2 with JSPM at the moment.

**Comment by guybedford** [comment] 2015-11-16 10:41
Setting dependencies through metadata is the way to resolve this properly to make the dependency tree explicit. Relying on execution order, even when this is guaranteed, is still a weak guarantee because circular references or dynamic imports will always alter execution ordering anyway making it a brittle solution.

Simple shimming can be done with:

```javascript
System.config({
  meta: {
    'plugin/src/pluginFile2': { deps: ['plugin'] }
  }
});
```

**Comment by chapati23** [comment] 2015-11-20 13:35
Won't work for me unfortunately.

JSPM v0.16.11
Systemjs v0.19.6
SystemJS-Builder v0.14.11

Copying relevant parts of config.js:

```javascript
    map: {
        "angular": "github:angular/bower-angular@1.5.0-beta.2",
        etc…
    }
    meta: {
        "angular": {
            "format": "global",
            "exports": "angular"
        },
        "ng-file-upload": { "deps": ["angular"] },
        "firebase": { "deps": ["angular"] },
        "angularfire": { "deps": ["angular"] }
    }
```

So I have the shims set up (as I understood @guybedford, if the `meta` object comes after the `map` object then I can use the mapped names) but after bundling as SFX my angular remains undefined.

`Uncaught ReferenceError: angular is not defined`, if I look through the bundle then I don't see angular defined globally.

This definitely did work before. Unfortunately I can't accurately reproduce the last working version as I upgraded a bunch of versions over the last weeks and hadn't bundled since then.

**Comment by guybedford** [comment] 2015-11-23 12:03
Resolved in https://github.com/jspm/jspm-cli/issues/1294, release pending.

**Closed by guybedford** 2015-11-23 12:03 UTC
Labels: support

**Comment by chapati23** [comment] 2015-11-23 12:46
:+1:
