### ISSUE TITLE
package.json prefix with no dependencies causing problems with "jspm install"

### ISSUE THREAD

**Issue by stefanr** [jspm/jspm-cli#561] opened 2015-03-02 22:40 UTC
If no dependencies are set within the jspm prefix inside the package.json `jspm install` uses top level dependencies.

```js
{
  "dependencies": {
    "some-module": "*"
  },
  "jspm": {
    "dependencies": {}
  }
}
```

Running `jspm install` causes dependencies inside jspm to be removed:

```js
{
  "dependencies": {
    "some-module": "*"
  },
  "jspm": {
  }
}
```

After running `jspm install` again jspm tries to install `some-module`.

If the jspm prefix is set only settings inside this prefix should be considered by `jspm`.

**Comment by guybedford** [comment] 2015-03-03 09:16
@stefanr this is actually by design. To explain - the `jspm` property doesn't take preference, rather it acts as an override of the underlying package.json file.

**Comment by stefanr** [comment] 2015-03-03 23:43
OK, so as soon as `jspm install` is not removing empty dependencies anymore this might not be an issue.

But this could cause problems if new properties are introduced in newer releases of `jspm`. They might already be used whitin regular `package.json` files for whatever reason.

I think a property to disable the override mode would be a good idea. Something like `"strict": true"` which tells `jspm` not to look further except for some default `npm` properties like name, version and so on. In order to tell `jspm` which properties to use something like this would be an idea:

```json
{
  "foo": "bar",
  "jspm": {
    "strict": true,
    "foo": { "@ref": "foo" }
  }
}
```

**Comment by sochka** [comment] 2015-03-07 00:21
+1, why does `jspm install` remove my empty `dependency` property? On the next `jspm install` things are broken.

**Comment by sochka** [comment] 2015-03-07 12:21
I ended-up putting some fake dependency just to make things work... I think this is most definitely a bug, even if considered as a feature.

**Comment by guybedford** [comment] 2015-03-09 13:05
Thanks, yes this is a bug that should be resolved.

**Comment by guybedford** [comment] 2015-03-17 11:44
Fixed in https://github.com/jspm/jspm-cli/commit/d44511bb2bd7a2e596d0da27f03d51c8bddf5aef.

**Closed** 2015-03-24 23:38 UTC
