### ISSUE TITLE
Package.json override workflow

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#398] opened 2015-01-13 11:11 UTC
Despite my previous resistance this is probably very necessary.

The form would be:

```json
{
  "overrides": {
    "github:components/jquery@2.0.0": { ... }
  }
}
```

Here's a suggested workflow:

1. When running `jspm -o`, add the override into the package.json. Also check for overrides from the package.json during install for all dependencies, this will work with the package hashing well.
2. While there are overrides in the package.json, show a warning message after every install that overrides are present and that shared dependencies may not work as expected until the overrides are merged into the registry.
3. `jspm register-overrides` can generate a PR into the registry for all current overrides in the package.json, returning a link to the PR. If the registry is not on GitHub, this would need to be done manually, and instead they would just be given the branch name. It could behave similarly to the jsDelivr bot - https://github.com/jsdelivr/jsdelivr/pull/3038.
4. On the next install, when overrides in the package.json match the override looked up in the registry, these can be automatically cleared out (perhaps with a prompt asking the user about this first, or at least with a message).

If I've missed scenarios in the above please let me know.

The nice thing is this workflow can be implemented gradually as well from 1 - 4.

**Comment by theefer** [comment] 2015-01-17 18:00
Sounds great. I understand your initial resistance to having local overrides, but I also believe it's going to be hard to justify not having a way to share such overrides (e.g. private repos, etc) without going through the registry. Also makes staging/testing an override easier. I like the idea of making it easy to submit an override to the registry.

Slight OT, though related: I had this idea of a web app that'd help configure jspm dependencies.

Something like:

1. Search for a given name (e.g. `moment`)
2. Results show if it's already present in the registry. If not, it uses npm search and bower search to suggest npm/github endpoint that may be what you want.
3. Picking one of the npm/github/other suggestions uses SystemJS and jspm.io to try and load the given endpoint.
4. The UI lets you browse the resulting package, in particular available files, default main, and their respective exports.
5. Any error (missing main, no exports found, loading error, dep not found, etc) is highlighted, with the option to solve them (pick the main file, configure a dependency, set the `lib`, override the format, etc). The package is then reloaded with the overrides so you can review if all is working as expected.
6. Submit a PR to the parent repo and/or the jspm registry to record the alias and any override. Possibly (as per this PR) allow downloading the override locally (as a `jspm` command to run?) in the meantime.

I haven't given it a try yet, so I don't know how much change is needed to make all of this possible. I suspect not much? Possibly 5. requires a way to apply the override in the CDN though?

I don't know if this sounds like a good idea to other or not, so any feedback is welcome! Also apologies for hijacking this PR, I might open a new Issue if people feel like this is worth a try. 

/cc @oliverjash

**Comment by guybedford** [comment] 2015-01-18 09:40
@theefer yes a guided visual tool here would be ideal certainly! @Jarreddebeer started something for this at https://github.com/jspm/registry/issues/87.

Ideally it would be more guided as you say, linking in to the automatic-PR system.

Overrides are refreshed on the CDN through a URL-based task request I run on updates, it could certainly be triggered from an API.

**Comment by theefer** [comment] 2015-01-18 18:58
> Overrides are refreshed on the CDN through a URL-based task request I run on updates, it could certainly be triggered from an API.

But is there a way to request a package, passing custom temporary overrides? I'm thinking of how to implement 5. if loading packages from the CDN, but needing to test custom overrides, which IIUC need to be applied at the CDN level rather than on the client.

**Comment by guybedford** [comment] 2015-01-19 09:44
@theefer, right yeah that would require a sandbox CDN with overrides as query params perhaps.

**Comment by guybedford** [comment] 2015-01-23 10:11
It's a little worrying that VERY few people are posting overrides. This is obviously way to hard for most to work out. Improving these workflows to make libraries work easily is crucial.

**Comment by theefer** [comment] 2015-01-23 10:35
I agree.

How much does the jspm-cli warn users when installing packages that need overrides (missing main, dependencies, configure exports, etc)? It feels like the right place to tell people "hey, I suspect this won't work, maybe you want to try this?". Obviously not everything can be detected, although maybe quite a lot can be if we're prepared to do enough static analysis?

**Comment by matthewp** [comment] 2015-01-23 12:50
Local overrides is very important. Having an easier way to push them to the registry is a good idea but users shouldn't have to wait for a PR to get merged before their app will work.

**Comment by Jarreddebeer** [comment] 2015-01-23 19:48
I agree with Matthew. Testing that the override actually works is also
important. Being able to create a local override on the spot and allow the
developer to continue developing with it would absorb a 'separate testing
phase', and a pull request for the override could be sent as an after
thought once they're sure it's working.

**Comment by Aaike** [comment] 2015-01-26 14:55
:+1: for local overrides !

And having a `jspm publish` command much like `npm publish` would also be nice , single command to add stuff to the registry.

I'm just thinking out loud here but would it be a good idea to **not** use a github repo for the registry ? but rather have the data stored in mongodb or something, and setup a rest api to interact with it ? Then people can implement their own interfaces for jspm, and the cli can easily do more powerful stuff by interacting with a backend, opening many doors...
im just worried that a github repo might not be good enough at some point.

**Comment by speigg** [comment] 2015-01-27 02:02
:+1:

**Comment by smajl** [comment] 2015-02-04 14:48
Maybe a little OT, sorry about that, but will this enable **overriding what is downloaded from a package endpoint**?

E.g. when I do `jspm install bootstrap` I only want to download `less` folder with styles, so will it be possible to use this in my `package.json`? Now this is ignored and removed:

```
...
    "overrides": {
      "bootstrap": {
        "directories": {
          "lib": "less"
        }
      }
    }
...
```

Or is there already some other easy (config-like) way to do that elsewhere? Thank you.

**Comment by guybedford** [comment] 2015-02-04 14:49
Yes exactly custom overrides like that would be supported, but the goal is to heavily discourage custom overrides as it means your code is no longer sharable.

**Comment by smajl** [comment] 2015-02-04 15:02
No problem here, cause it's closed source. Anyway I get that local overrides should be an edge case, but I always needed override here and there when repo owner do not expose exactly what I want (like in Bootstrap case).

Looking forward to this, thanks for the info.

**Comment by guybedford** [comment] 2015-02-04 15:08
The issue still happens when you have another dependency that needs bootstrap and expects it to have a certain structure.

If the repo owner doesn't provide what you need, I'd suggest rather forking and using your own forked package.

**Comment by jpdesigndev** [comment] 2015-03-05 04:52
@guybedford I just don't know how long this logic can hold up.

For example: 

With `famous` there is a [registry override](https://github.com/jspm/registry/blob/master/package-overrides/github/Famous/famous%400.3.5.json) for `0.3.5`. That will work for some, but, for me, it doesn't work at all. [See this issue](https://github.com/Famous/famous/issues/617). I'm loving jspm thus far, but resistance to local overrides is becoming a huge hurdle. I've been stumped for an hour, and came across this issue.

**Comment by guybedford** [comment] 2015-03-05 10:27
@jpdesigndev let's follow your specific issues with Famous at https://github.com/jspm/registry/issues/183. Please let me know what exactly is not working for you with Famous on that issue and lets get the override updated.

As for the override workflows, I know creating overrides is hard work and can be frustrating if you're not aware of all of the details in play. Specifically in your case, it sounds like the override changes made 8 days ago have affected an existing project for you? My sincere apologies if this is the case - this was breaking the usual convention of always ensuring overrides are backwards-compatible, which we typically aim never to do.

**Comment by jpdesigndev** [comment] 2015-03-10 02:36
@guybedford 

No need to apologize at all :)

Now, I'll try to address the issue coherently.

[Line 3](https://github.com/jspm/registry/blob/master/package-overrides/github/Famous/famous%400.3.5.json#L3) of the `0.3.5` famous registry override is `"main": "dist/famous-global"`. This points to the global version of famous, which may be great for some. But, I prefer to load my dependencies a la carte from the `src`. I had this working via override, and I assumed overrides were persisted. Then, on the next `jspm install`, my override was lost. That's what brought me here. After some reading, I've seen that you have been "resistant" (there may be a better word) to persisting overrides. I appreciate that you would like to address the Famous issue directly, and that may be the only override I ever need. That being said, it concerns me that there is no way for me tell jspm to treat others' packages the way I'd like them to be treated. I don't think it's "good enough" to send PRs/fork others' projects, or add everything I need for my specific application to the override registry. Perhaps, I'm wrong, but it can feel quite restrictive instead of liberating ATM. 

These are just my thoughts. Let me know where I'm missing something important. You've spent a great deal of time on this, and you have done a fantastic job. Thank you.

**Comment by guybedford** [comment] 2015-03-11 13:56
@jpdesigndev the way to do this is with:

```javascript
import Timer from 'famous/src/utilities/Timer'
// etc
```

The reason we had to change this was because some users want to be able to load the full dist in one, while others want the individual files. Altering it to provide both this way was the change that broke this code for you.

As mentioned, overrides are designed not to be changed, so this shouldn't have broken your existing code. It's like a patch release altering the folder structure of a package - it's not the rules of the process.

Note that overrides are designed to become obsolete in future as packages manage their own package.json options for jspm.

**Comment by jpdesigndev** [comment] 2015-03-11 20:02
@guybedford Ah, I see. Your example makes sense. So, for this case, that would work. Do you see any value in allowing jspm users to declare how they would like a given package to be handled?

Your "happy path":
Public overrides until package authors see the value in configuring their own package for jspm.

From my perspective the "happy path" would read:
Public overrides until package authors see the value in configuring their own package for jspm. In addition, if neither of those suit your needs, you can write your own overrides to accommodate the needs of your application.

The convention over configuration approach is great, but will eventually break down when those conventions don't serve the intended purpose.

Thoughts?

**Comment by guybedford** [comment] 2015-03-12 09:40
@jpdesigndev if you think about it, we only have one codebase for a package. The override is like a part of the codebase that was published. Expecting custom overrides is like saying you want jQuery to change the name of its `dist` folder or something like that. If you don't like the way something is published to the public registry then that is when forking comes in.

**Comment by guybedford** [comment] 2015-03-12 09:41
Also the override complexity specifically exists on GitHub right now because of the lack of modularity conventions. A dedicated jspm registry would not need such a concept.

**Comment by speigg** [comment] 2015-03-12 18:38
I think if two packages in the same project want to load the same third party package using two different overrides (which are incompatible with each other) it should "just work".

**Comment by jpdesigndev** [comment] 2015-03-12 20:33
@guybedford said:
> if you think about it, we only have one codebase for a package.

So, yes, one codebase. Unless you look at it a bit differently. For example, famous tagged at `0.3.5` ships a `dist` folder and a `src` folder. Thankfully, the src folder is extremely modular, and you can take advantage of SystemJS's ability to load amd deps. So, in a perfect world, I could choose to use `dist` or `src` with manual overrides. The same codebase represented two different ways. Therefore, if I have my own build process, want to be smart about what I include, and/or just want the freedom to include deps as I need them, I would choose the `src` route. 

@guybedford said:
> Expecting custom overrides is like saying you want jQuery to change the name of its dist folder or something like that.

I'll stick with Famous as an example at the risk of portraying this a Famous specific concern.

I don't think it's that complex. It's more like me saying I want to use the included `src` folder instead of `dist`.

@guybedford said:
>  If you don't like the way something is published to the public registry then that is when forking comes in.

Good point. I was thinking you were referring to forking the packages. I can certainly fork the registry assuming jspm can be configured to use another registry which I think I saw somewhere in the docs.



Lastly, all of this assumes that I, as the engineer on my project am willing to accept the side effects of using a package how I'd like to use it contrary to how the registry override would like me to use it. Taking Famous as a great example. The registry override suggests that Famous should be used as global. But, part of what we're all doing here is using ES6, amd, and commonjs modules. Projects, like Famous, that give you the option are a perfect reason to allow for custom overrides.

In any case, you clearly don't feel the same way, and I respect that. You don't owe me anything. I just wanted to get my point across which I feel I've done. For now, forking the registry seems to be a good workaround.

**Comment by guybedford** [comment] 2015-03-13 09:32
@jpdesigndev I promise there is a reason to all this and it is because you can only create a consistent dependency management system if when two packages expect the same dependency name, they get exactly the same interface for that dependency. Arbitrarily adding overrides alters this property.

I completely accept though that there are situations where this does not apply, and this issue is exactly tracking ways to allow persistent overrides, while not being heaily encouraged, very simple and painless to accomplish to create.

In the mean time, forking the registry is also a valid option as well.

**Comment by guybedford** [comment] 2015-03-13 09:33
@jpdesigndev specifically for the Famous case - the change was made to allow `import 'famous'` to use the global and `import 'famous/src/blah'` to use a specific module.

**Comment by speigg** [comment] 2015-03-13 12:29
> I promise there is a reason to all this and it is because you can only create a consistent dependency management system if when two packages expect the same dependency name, they get exactly the same interface for that dependency. Arbitrarily adding overrides alters this property.

Only if overrides have global scope. Is there any reason why one dependency can't map "famous" to "famous/dist/famous-global"

**Comment by guybedford** [comment] 2015-03-13 12:31
@speigg can you clarify what you mean here?

**Comment by speigg** [comment] 2015-03-13 12:34
Sorry, accidentally posted before I finished typing. Please read the edit.

**Comment by guybedford** [comment] 2015-03-13 12:51
Right - so you are saying you'd like the map config to be able to point to a custom main? Specifically for Famous, `famous/src/index` isn't an entry point though?

Dependency mappings are designed to be package mappings - they need to use the same main entry point.

That said, you can use map config within a package's configuration to do this:

```json
{
  "map": {
    "famous": "famous/src/blah"
  },
  "dependencies": {
    "famous": "..."
  }
}
```

**Comment by speigg** [comment] 2015-03-13 13:14
>Right - so you are saying you'd like the map config to be able to point to a custom main? 

No, I'm saying that the default config for a package is consumed should by determined by that package, but the final config should be determined per consumer of that package (if the defaults are not desired). 

> Specifically for Famous, famous/src/index isn't an entry point though?

So, for famous, the default configuration could be to map "famous" to "famous/src" (the point in this case is not to make `import 'famous'` do anything useful, but to allow (`import famous/core/Engine`, for example). If a certain package prefers to use famous-global, it should be able to override the famous configuration _for that package only_, mapping `famous` to `famous/dist/famous-global` (allowing `import 'famous'` to import the entire famous-global library—but only in that package). The problem with overrides, imo, is that they are global. I believe the scope of an override should be restricted to the package which requires the override.

**Comment by speigg** [comment] 2015-03-13 13:23
What I am suggesting would require jspm to not modify the source files of packages (we discussed this possibility in another thread), allowing them to be imported flexibly by different packages in different ways.

**Comment by guybedford** [comment] 2015-03-13 13:31
@speigg specifically for this Famous use case, I'd suggest https://github.com/jspm/registry/issues/265.

In terms of enabling consumers to have the freedom not to seek universal package meaning through the registry when they don't need it, that is exactly what this issue is for and it will be supported.

**Comment by speigg** [comment] 2015-03-13 14:00
I'm not talking about "universal" package configs. I'm talking about package-scoped configs. This has nothing to do with the registry :)

**Comment by speigg** [comment] 2015-03-13 14:09
Maybe using famous as an example is limiting. Here is a more abstract example:

Package A wants to map x to "some/module/somewhere/" ... Then in Package A (and ONLY in Package A) `import 'x'` means imports from "some/module/somewhere"
Package B wants to map x to "a/different/module/somewhere/" ... Then in Package B (and ONLY in Package B) `import 'x'` means imports from "a/different/module/somewhere/"

Package C should be able to import Package A and Package B without any issues. Somehow, this should be possible.

**Comment by guybedford** [comment] 2015-03-13 14:13
@speigg yes this is supported and a key feature in jspm. A custom map like in https://github.com/jspm/jspm-cli/issues/398#issuecomment-78957352 combined with the dependency object would provide this. See also https://github.com/jspm/jspm-cli/wiki/Installing-Packages#requiring-packages.

**Comment by speigg** [comment] 2015-03-13 16:00
If this is already supported by jspm then it should be possible for package A to import famous/src/core/Engine as `import "famous/core/Engine", package B to import famous/dist/famous-global as `import "famous", and package C to import both package A and package B. I don't see where the link you provided would help with this. 

Can a custom map look like the following in package A?

{
  "map": {
    "famous": "famous/src"
  },
  "dependencies": {
    "famous": "..."
  }
}

And like this in package B? 

{
  "map": {
    "famous": "famous/dist/famous-global"
  },
  "dependencies": {
    "famous": "..."
  }
}

If so, that would work.

**Comment by guybedford** [comment] 2015-03-13 16:36
Yes exactly - that's this issue I made here https://github.com/jspm/registry/issues/265.

**Comment by jpdesigndev** [comment] 2015-03-13 16:41
Ah, so `map`. That's a new one to me. https://github.com/jspm/registry/issues/265 looks like it could solve some issues I'm having. 

So, forking the registry, submit a PR, hope others like it is the best bet. Otherwise, forking in perpetuity. That seems like a sane approach.

**Comment by guybedford** [comment] 2015-03-22 12:08
Implemented in https://github.com/jspm/jspm-cli/commit/505ef56836f09165cacf4548ff4c95db62676832.

I've split out the automatic PR system into issue https://github.com/jspm/jspm-cli/issues/605. The "wizard" is being tracked in https://github.com/jspm/jspm-cli/issues/395.

**Closed** 2015-03-24 23:34 UTC

**Comment by brianfeister** [comment] 2015-04-17 17:36
Are the implementation details surround `overrides` in `package.json` documented somewhere? I can't tell how this landed.

**Comment by trusktr** [comment] 2015-05-31 19:14
Oh, does this work now? I gotta get caught up with jspm. This is great, because from everyone that I've talked to in person that has experience with jspm the general consensus was that jspm seems really cool, but it's so un-configurable. Seriously, that was the unanimous feeling talking to people individually without each person having knowledge of my conversations with the others, and they all felt the lack of configurability was the show stopper for them.

This feature is a big deal. I know you had friction against it, but we need to be able to just move forward on project without worrying about how to deal with overrides that don't exist yet, without having to wait for registry PRs and without having to configure custom registries.

In fact, this feature IMHO encourages the creation of overrides, which will encourage registry PRs in general. It's so much easier to work with json overrides than command-line overrides. 

I'll upgrade jspm for my project soon and test this out. This might eliminate the nasty `jspm_install.sh` file I have in my project.

**Comment by brianfeister** [comment] 2015-05-31 20:15
I'm using this in my project. It works.

**Comment by trusktr** [comment] 2015-05-31 23:03
@brianfeister Awesome. I'll point this feature out to people for sure. @guybedford Is this documented somewhere?

**Comment by guybedford** [comment] 2015-06-06 09:29
@trusktr no this isn't documented. Override workflows still need some love.

**Comment by trusktr** [comment] 2015-06-06 18:32
@guybedford I was about to try to give it some love by adding details to the wiki, but it's not editable!

**Comment by guybedford** [comment] 2015-06-08 17:50
@trusktr yes there were some bad edits made so had to lock it down! Where were you looking to put it?

**Comment by trusktr** [comment] 2015-06-08 20:47
@guybedford I think in the [somewhere](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#testing-configuration) in the registry wiki, but I think it would need a little bit of refactoring so overrides aren't just about "testing configuration" but more like a way to persist configuration. Maybe "Package Overrides" would be it's own section instead of "Testing Configuration". It would be obvious that package maintainers could add official overrides to the registry, but also obvious that we can always override official overrides with your own.

In general, I think it'd be a lot better if the jspm-cli and and registry wikis were united into one so things are easier to navigate, and host it on jspm.io, like how Webpack has it's own dentralized docs at http://webpack.github.io/docs.

**Comment by guybedford** [comment] 2015-06-08 20:52
@trusktr thanks I've updated the wiki. Yes the goal is to have a separate docs site, and make the repo docs just pure API docs, but will only do this work when we reach a nice round 1.0.

**Comment by trusktr** [comment] 2015-06-08 20:57
@guybedford Okay, cool.

Where'd you make the wiki change? Now that I think about it, I think the best place for it is at https://github.com/jspm/jspm-cli/wiki/Installing-Packages, as opposed to configuring a package for the registry, but each section (https://github.com/jspm/jspm-cli/wiki/Installing-Packages#other-options and https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#testing-configuration) should ideally link to each other. Currently https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#testing-configuration doesn't link to the other.

**Comment by trusktr** [comment] 2015-06-27 05:05
Just wanted to comment that you can use just the package name:

```js
{
  "overrides": {
    "jquery": { ... }
  }
}
```

**Comment by trusktr** [comment] 2015-06-28 21:50
@guybedford Can you consider making two new repos for the jspm-cli and registry wikis, so that we can make pull requests? Then, after those PRs are merged in, you can simply [push to the actual repo wikis](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/). That would be nice for contributions.

**Comment by guybedford** [comment] 2015-06-29 17:54
@trusktr thanks for pointing out this feature, I wasn't aware that wikis are git repos! Kind of set on the current workflow for now though, but will definitely re-asses with this in mind when updating the format next.

**Comment by trusktr** [comment] 2015-06-29 20:59
Yeah, that'd be super cool to be able to contribute docs in such a way that you can still approve changes via PR so that the docs don't have changes you don't like.

**Comment by smajl** [comment] 2015-08-19 10:55
I thought that this could override `files` definition in a repo. But if repo already does `"files": ["A", "B"]` subset from `[A, B, C]` files then I cannot get hold of `C` files, only files from that subset (`A, B`). :( This is by design or could be something be done about this?

Example: JSPM Bootstrap package exports files from `css`, `fonts` and `js` directory. I don't need any of that, contrary I need `less` directory.

**Comment by guybedford** [comment] 2015-08-21 13:07
@smajl you should do a full override of files repeat - `jspm install bootstrap -o "{files:["A", "B", "C"]}"` as no merging is done for the overrides. Note also that Bootstrap may be using the ignore property which would be worth checking if that needs an override too.

**Comment by smajl** [comment] 2015-08-26 13:39
@guybedford I just cant make it to work. :( I am doing:
`jspm install bootstrap -o "{ files: ['css', 'fonts', 'js', 'less'] }"`

But it downloads only these three directories defined in the [registry](https://github.com/jspm/registry/blob/master/package-overrides/github/twbs/bootstrap%403.3.4.json) (`css`, `fonts`, `js`) and also in Bootstraps [package.json](https://github.com/twbs/bootstrap/blob/master/package.json). I checked for the ignore property in Bootstrap repo and there seems to be nothing affecting the `less` directory.

Can you test that for yourself, please?

**Comment by guybedford** [comment] 2015-08-26 15:58
@smajl Bootstrap is loaded from the release assets at https://github.com/twbs/bootstrap/releases, as jspm-github will use release archives for tags when provided. So if you're using the current bootstrap I don't believe the less files are in there at all. You'd need to use another source of bootstrap that does contain these files.

**Comment by smajl** [comment] 2015-08-31 10:53
@guybedford Oh, I see... the release archive truly does not contain that. :( Thx for the info.
