### ISSUE TITLE
0.17.0-beta.13: jspm build --watch only watches entry file

### ISSUE THREAD

**Issue by m-a-r-c-e-l-i-n-o** [jspm/jspm-cli#1717] opened 2016-04-13 18:15 UTC
I'm issuing the following command in my setup:
`jspm build src/server/index.js src/server/bundle.js --node --dev --watch`

The entry file `src/server/index.js` contains:
`import example from './example'`

Changes to `./example` does not trigger an update, it's as if it's not being watched. But changes to `src/server/index.js` works just fine.

Issue seems to be present for both "watchman" and node's native watch.

The "bundle" command `jspm bundle src/client/index.js src/client/bundle.js --dev --minify --watch`, which I use for the client side stuff, works as expected.

jspm version: 0.17.0-beta.13

**Comment by guybedford** [comment] 2016-04-13 21:50
Thanks for posting, yes this sounds like a duplicate of https://github.com/jspm/jspm-cli/issues/1718. See https://github.com/jspm/jspm-cli/pull/1719 for a patchable workaround.

**Closed by guybedford** 2016-04-13 21:50 UTC
