### ISSUE TITLE
`jspm.config.js` and `jspm.browser.js` placed in wrong directory

### ISSUE THREAD

**Issue by teohhanhui** [jspm/jspm-cli#1456] opened 2016-01-22 06:42 UTC
0.17.0-beta.3

`jspm init`
```
Init Mode (Quick, Standard, Custom) [Quick]: Standard
Local package name (recommended, optional): app
package.json directories.lib [src]: src
package.json directories.baseURL (optional): public
package.json directories.packages [public/jspm_packages]: public/jspm_packages
System.config browser URL to src  [/src]: /app

     Enter the browser URL for the jspm_packages folder.

System.config browser URL to public/jspm_packages [/public/jspm_packages]: /jspm_packages
System.config local package format (esm, cjs, amd): esm
System.config transpiler (Babel, Traceur, TypeScript, None) [babel]: babel
     
ok   Verified package.json at package.json
     Verified config files at public/jspm.config.js and public/jspm.browser.js
     Looking up loader files...
       system.js
       system-polyfills.js
       system.src.js
       system.js.map
       system-polyfills.js.map
       system-polyfills.src.js
     
     Using loader versions:
       systemjs@0.19.17
ok   Loader files downloaded successfully
```

Project structure:
```
|-- package.json
|-- public
|   |-- app
|   `-- jspm_packages
`-- src
```
where `public/app` is a relative symlink to `../src`

But `jspm.config.js` and `jspm.browser.js` end up in the project root directory instead of `public`

**Comment by gcnm-pgeil** [comment] 2016-01-22 10:09
That's not a bug. You just get the meaning of baseURL wrong. SystemJS needs to know where the "root" directory for all the source files is. It needs this for translating a symbolic module names and relative file paths to the actual (absolute) file path or URL. And since your source root directory may reside anywhere, we use the baseURL to specify the location to this root directory.

In your case, the project root is simply not the source root.

**Comment by teohhanhui** [comment] 2016-01-22 10:23
@gcnm-pgeil

> baseURL: This should be set to the public folder where your server will serve from, relative to the package.json file.
https://github.com/jspm/jspm-cli/blob/0.17.0-beta.3/docs/getting-started.md

And I've used the same directory structure in a previous project with jspm 0.16 (with successful loading and bundling), so I don't think I got it wrong here.

**Comment by teohhanhui** [comment] 2016-01-22 10:26
Also, look at this line from the output above:

```
Verified config files at public/jspm.config.js and public/jspm.browser.js
```

**Comment by teohhanhui** [comment] 2016-01-22 11:50
There's a rule that `directories.lib` must be inside `directories.baseURL`. It's still not enforced during `jspm init`.

That is what's causing the problem.

**Comment by guybedford** [comment] 2016-01-24 17:46
@teohhanhui thanks, fixed in https://github.com/jspm/jspm-cli/commit/61d095f4365ce03e79e7e64f629c4f95aa2124a6, will post out an updated beta tomorrow

**Closed by guybedford** 2016-01-24 17:46 UTC
