### ISSUE TITLE
jspm outdated / jspm inspect --json command

### ISSUE THREAD

**Issue by Anachron** [jspm/jspm-cli#471] opened 2015-02-03 07:31 UTC
I'm not quite aure I understand JSPM correctly, but shouldnt it have an outdated and update command? The update command could use the json output of outdated :)

**Comment by guybedford** [comment] 2015-02-03 08:45
There is an `update` command.

For an `outdated` command, do you mean giving a report on the dependencies?

**Comment by Anachron** [comment] 2015-02-03 09:05
@guybedford yup, exactly. I would also like to get a list of all packages and all the current versions, so I can store them in a file and process them when needed. I plan to write a mimosa plugin for JSPM.

For the updated command, it does not seem to be able to get a result of the packages that are updated? I'm looking for something like a JSON to retrieve the data.

The use-case here is an external tool that will check is JSPM has something to update, and if so, store it in a file so that it can be used further in other workflows.

**Comment by guybedford** [comment] 2015-02-03 09:09
@Anachron sure, would be interesting to see the mimosa work!

You can use `jspm inspect` to get a list of all installed packages and versions.

The update command does provide a summary in the output showing any dependency changes of the format `endpoint:package old.version -> new.version`.

Effectively an update report would be like running update without actually making the changes. Perhaps `jspm update --test` or something like that? What's the common name for this again?

**Comment by guybedford** [comment] 2015-02-03 09:10
@Anachron in terms of the outputs, we could provide the useful outputs for these through the API calls - https://github.com/jspm/jspm-cli/blob/master/api.js#L79. If you need JSON output for the install changes / `jspm inspect` etc, API contributions are welcome here.

**Comment by Anachron** [comment] 2015-02-03 09:23
@guybedford I just started to use JSPM because it's used by Aurelia and I do really like the ES6 syntax, so I naturally enjoy this package manager. 

It would help me a lot if there would be a simple switch for `jspm update`, `jspm inspect` and `jspm outdated`, like `--format json` which enables output in a simple JSON. 

I do like the idea of hooking into the api like you suggested, but since I am not too familiar with JSPM yet, I am not sure it's the best way. 

About the `jspm update --test`, I requested something similiar to bower, and they do not quite see  the need (sadly): https://github.com/bower/bower/issues/1138

I do like `jspm outdated` more than `jspm update --test`, as test suggest seems to be liked to update, as if it would check whether it could update, not whether it has something to update.

**Comment by guybedford** [comment] 2015-03-17 08:28
https://github.com/tjunnone/npm-check-updates

**Comment by rquast** [comment] 2015-06-10 21:37
I'd like to put a +1 in for this. Coming from Java, I'm used to having the "mvn versions:display-dependency-updates". This is particularly useful for any large app where you don't have the time to go and do the research on what components have been updated each time you do a release.

**Comment by myitcv** [comment] 2015-07-13 18:06
@guybedford - `npm-checkupdates` has exactly the semantics I would expect from such a feature

**Comment by kburson** [comment] 2015-07-21 19:58
`npm-check-updates` will list all your `(package.json).devDependecies` that can be updated, and with the -u switch it can auto upgrade the package.json file.

`npm-check` will interactively allow you to select which upgrades to latest versions you want to accept, then upgrade your package.json and install those updates.

neither of these will inspect the `(package.json).jspm.[dependencies|devDependencies]`.

I can use either of the former tools to update any build tool dependencies, but not for 'runtime' browser-libs.

What solution can we propose to extend this functionality to the browser-libs managed by jspm?

**Comment by screendriver** [comment] 2015-09-21 15:07
Duplicate of #407 ?

**Comment by glen-84** [comment] 2015-11-09 21:01
> Perhaps jspm update --test or something like that? What's the common name for this again?

`--dry-run` ?

**Comment by glen-84** [comment] 2015-11-18 08:32
I use npm-check-updates, and we really need something similar for JSPM.

**Comment by gersongoulart** [comment] 2015-12-13 22:39
+1 for this feature. Here's another excellent model to look at: https://www.npmjs.com/package/npm-check

**Comment by cohenw** [comment] 2016-01-04 16:24
I've just used https://github.com/pauldijou/outdated which comes pretty close to wh

**Comment by jolafrite** [comment] 2016-01-11 07:52
+1

**Comment by mikz** [comment] 2016-02-23 10:41
There is [`npm outdated`](https://docs.npmjs.com/cli/outdated) which works pretty well for me. Maybe hooking into that and reusing it would work.

**Comment by johnmanko** [comment] 2016-02-27 23:22
Output like this would be fantastic. The first line is the currently installed version, followed by future releases (regardless of version number) and a link to the release:

```

                   github:Leaflet/Leaflet 0.7.4 on 09.01.2015 [https://github.com/Leaflet/Leaflet/releases/tag/v0.7.4]
                                          0.7.5 on 09.02.2015 [https://github.com/Leaflet/Leaflet/releases/tag/v0.7.5]
                                          0.7.7 on 10.26.2015 [https://github.com/Leaflet/Leaflet/releases/tag/v0.7.7]
                                   1.0.0-beta.2 on 10.24.2015 [https://github.com/Leaflet/Leaflet/releases/tag/v1.0.0-beta.2]

                 github:components/jquery 2.2.0 on 01.08.2016 [https://github.com/jquery/jquery/releases/tag/2.2.0]
                                    3.0.0-beta1 on 01.14.2016 [https://github.com/jquery/jquery/releases/tag/3.0.0-beta1]
                                         1.12.1 on 02.22.2016 [https://github.com/jquery/jquery/releases/tag/1.12.1]
                                          2.2.1 on 02.22.2016 [https://github.com/jquery/jquery/releases/tag/2.2.1]
```

**Comment by piuccio** [comment] 2016-04-21 10:25
I was hoping any of the other `npm-check...` project would start supporting jspm, but nothing is moving.
I've created my own package, [jspm-check-updates](https://github.com/piuccio/jspm-check-updates). It's quite rubbish and I probably won't maintain it, but works for me!

Hopefully it gets things moving.

**Comment by matthew-dean** [comment] 2016-10-28 21:12
I'm also confused why there isn't something like this. If I update a Github repo which is a dependency, which command grabs those latest updates? It seems like JSPM provides nothing here.

**Comment by guybedford** [comment] 2019-04-24 02:07
jspm upgrade is likely the best workflow for this.

**Closed by guybedford** 2019-04-24 02:07 UTC
