### ISSUE TITLE
Unclear warnings about registry property not set with jspm install

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#1015] opened 2015-08-11 15:57 UTC
Since upgrading from JSPM 0.16 beta 3 to beta 7, we are getting the following errors:

```
warn github:monospaced/angular-elastic@2.5.0 dependency installs skipped as it's a GitHub package with no registry property set.
If the dependencies aren't needed ignore this message. Alternatively use the npm registry version at jspm install npm:angular-elastic@^2.5.0 instead.
...
warn github:christopherthielen/ui-router-extras@0.0.14 dependency installs skipped as it's a GitHub package with no registry property set.
If the dependencies aren't needed ignore this message. Alternatively use the npm registry version at jspm install npm:ui-router-extras@^0.0.14 instead.
```

Even though further below:

```
ok   Installed angular-elastic as github:monospaced/angular-elastic@^2.4.2 (2.5.0)
...
ok   Installed angular-ui-router-extras as github:christopherthielen/ui-router-extras@^0.0.14 (0.0.14)
```

I'm not sure what that warning really means. Does the registry property always need to be set via an override now? I'm surprised that it's somehow set for [all other packages we install](https://github.com/guardian/grid/blob/master/kahuna/package.json#L6-L33)...

**Comment by guybedford** [comment] 2015-08-12 11:36
I just tested this out against beta.7 and I'm definitely only getting the first warning not the second. Are you sure you've fully updated?

This is a warning, not an error so you are free to ignore it. It is there to clarify that things might not work as expected, to help mitigate cases where a jspm install just doesn't work.

The cause is that `angular-elastic` is an npm package with a dependency on `angular`. That is when you install it, you would expect to also install `angular`. The warning is telling you that it hasn't installed any dependencies when it blatantly expects dependencies via the npm package.json information.

I guess you've shimmed it to work in your case, but not via an override as any override would have also silenced the message.

**Comment by guybedford** [comment] 2015-08-17 15:22
Closing as this is by design.

**Closed by guybedford** 2015-08-17 15:22 UTC

**Comment by nicklasb** [comment] 2015-08-28 18:51
I am also getting this, and while it only a warning, it actually skips installing dependencies?
So I would rather raise an error and not install the package at all, as there is no point in installing packages where the dependencies aren't satisfied?
Also:
#1. I am getting this on packages that *has* the registry property set in the package.json ( [github:Textalk/angular-schema-form@0.8.8](https://github.com/Textalk/angular-schema-form)
#2. I do *not* seem to get in in a package that *doesn't* have it set([npm:angular-schema-form-dynamic-select@0.11.7](https://github.com/OptimalBPM/angular-schema-form-dynamic-select)

The obvious differences between the two, of course is that one is npm, and the other is github? But why should that matter?

**Comment by guybedford** [comment] 2015-09-02 07:08
@nicklasb we treat packages on npm by the npm package.json rules, while packages on GitHub are given minimal rules. You should get a warning when installing `github:Textalk/angular-schema-form` that installing `npm:angular-schema-form` would be preferable, that's because npm packages should always be installed from npm.

**Comment by nicklasb** [comment] 2015-09-02 10:26
Thanks for you response.
What my beef is, is that it is only a warning, when it should be an error, since the consequence is so dire?

**Comment by guybedford** [comment] 2015-09-02 10:27
@nicklasb there are a lot of use cases where an npm project has a browser build that you want to use, and don't need any of the normal npm dependencies, that's probably the only valid use case of loading npm packages from GitHub instead of npm. So depending on which route the user it taking they may or may not want to continue along this path.

**Comment by nicklasb** [comment] 2015-09-02 10:34
Aha. Ok, thanks, then I understand.
