### ISSUE TITLE
Conflicting behavior for creating bundle with jspm and loading with systemjs

### ISSUE THREAD

**Issue by ahmedshuhel** [jspm/jspm-cli#853] opened 2015-06-17 22:11 UTC
The conflicting behavior of `systemjs` and `jspm` bellow are causing problems:

- When jspm creates bundle with `--inject` it creates relative to `baseURL` and does not consider the `paths`.
- When systemjs loads an injected bundle, it loads relative to `paths`(if set) not baseURL. 

Consider the paths for [skeleton-navigation](http://github.com/aurelia/skeleton-navigation)` for example:
```javascript
  "paths": {
    "*": "dist/*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  },
```
So when we run `jspm bundle app dist/bundle.js -i` it creates a bundle in the `dist` folder but get's injected in the `config.js` like:

```javascript
  "bundles": {
    "dist/bundle": [
      "npm:core-js@0.9.15/modules/$.fw",
      "npm:core-js@0.9.15/modules/$.dom-create",
 ```
> Note that, it did not consider the `paths`.

Now, when the application tries to load the bundle `systemjs` looks for an url like `dist/dist/bundle` as our `*` path is configured to `dist`. Thus fail to load.

On the other hand,
If we create a bundle with `jspm bundle app bundle.js -i`, this will create the bundle file in `baseURL` not in the `dist` folder, and application will look for the bundle with url like `dist/bundle.js` as the `*` path is set to `dist`. Again, the app will fail to load the bundle.

bundle when injected is treated as a regular module as long as path resolution of `systemjs` is concern. So, it makes more sense if `jspm` considers `paths` along side `baseURL` when `inject` is set to true. 

I have resolved this issue in another project changing jspm api, I would like to participate and make a PR, if you allow me. Thank you.

**Comment by guybedford** [comment] 2015-06-23 14:59
Perhaps you need to try `jspm bundle app dist/bundle.js` here.

**Comment by ahmedshuhel** [comment] 2015-06-24 05:48
Are you suggesting without `--inject`? Without inject it is not a problem because we are including the bundle manually. The problem I am having here is `with inject`. 

Considering the above `paths`, if we run `jspm bundle app dist/app-bundle.js -i` it creates a bundle in the dist folder but get's injected in the config.js like:
```javascript
  "bundles": {
    "dist/app-bundle": []
```
Which should be :
```javascript
  "bundles": {
    "app-bundle": []
```
As long as `SystemJS` is concern.

**Comment by guybedford** [comment] 2015-06-24 10:50
Ok so the issue is that the bundle is being named incorrectly, when it should follow the aliasing from the paths rules. This sounds like something we can fix then to reverse-apply paths on the bundle name.

**Comment by ahmedshuhel** [comment] 2015-06-24 21:39
You are right. `Reverse applying the path rule` is how I solved it in [aurelia-cli](http://github.com/aurelia/cli) which depends on jspm for bundling. I could make a PR for this if you like. Thank you.

**Comment by guybedford** [comment] 2015-06-24 21:46
A PR on this would be very welcome. The function to reverse-apply paths is provided at https://github.com/systemjs/builder/blob/master/lib/builder.js#L11 in SystemJS builder so should be possible to share here.

**Comment by ahmedshuhel** [comment] 2015-06-24 22:17
Thank you. I am on it.

**Comment by ahmedshuhel** [comment] 2015-06-29 07:40
@guybedford Could you please take a look at https://github.com/systemjs/builder/issues/214

**Comment by ahmedshuhel** [comment] 2015-07-02 07:18
@guybedford Could we update system-builder version for jspm that have systemjs/builder#214 fix? I need that to continue from here.

**Comment by guybedford** [comment] 2015-07-02 11:19
@ahmedshuhel I'd suggest running on master for now and I'm happy to take PRs on jspm that work against SystemJS builder master. Will do a release in the next week though definitely.

**Comment by ahmedshuhel** [comment] 2015-07-02 19:41
Great!

**Comment by cscleison** [comment] 2015-07-14 15:24
+1... any update on this?

**Comment by guybedford** [comment] 2015-07-14 16:10
This is fixed, just awaiting release.

**Comment by guybedford** [comment] 2015-08-10 19:30
Released in jspm@0.16.0-beta.6.

**Closed by guybedford** 2015-08-10 19:30 UTC
Labels: fixed pending release

**Comment by newduke** [comment] 2015-08-19 18:53
I believe fixing this broke some aspects of bundle creation.
Under 0.16.0-beta.3, I could 
```
`npm bin`/jspm bundle handlebars-templates build.js
```

but with this patch I get:
    Building the bundle tree for bundle.core...

err  Error: ENOENT, open '/Users/jordanweitz/udemy-django/static/src/udemy/js/jq/generated/handlebars.templates.js'
```

My `config.js`:
```
  "paths": {
    "*": "jq/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "handlebars-templates": "generated/handlebars.templates",
...
```

We have a bunch of legacy files under jq which assume jq to be the root, so I added a wildcard path for them.  This configuration works fine in runtime, but confuses paths at bundle time.

**Comment by newduke** [comment] 2015-08-19 20:31
@guybedford FYI

**Comment by newduke** [comment] 2015-08-19 22:02
@guybedford @kudos I made a small repository which demonstrates the issue.

```
➜  jspm1 git:(master) jspm bundle core
     Building the bundle tree for core...

err  Error: ENOENT, open '/Users/jordanweitz/jspm1/lib/index/main.js'
➜  jspm1 git:(master) jspm bundle ../index/main
     Building the bundle tree for ../index/main...

err  Unable to calculate canonical name to bundle file:///Users/jordanweitz/index/main.js
```

**Comment by guybedford** [comment] 2015-08-23 13:01
@newduke thanks for the detailed report - I've included a fix in https://github.com/systemjs/builder/commit/290b84bfb90a8786900e8652671a0aab36f7e5fc.

**Comment by newduke** [comment] 2015-08-24 16:45
Thank you, @guybedford!  Much appreciated.

**Comment by javadbat** [comment] 2018-09-04 08:02
so how we separate bundle path from bundle load URL?
for example "jspm bundle app /src/module/bundle.js @module/bundle" so in load jspm looking for @module/bundle in load?
