### ISSUE TITLE
`main` field in package.json isn't honored 

### ISSUE THREAD

**Issue by hgl** [jspm/jspm-cli#603] opened 2015-03-22 08:14 UTC
/foo/src/index.js
```js
export var a = 1;
```

/foo/package.json
```json
{
  "name": "foo",
  "version": "0.0.0",
  "main": "index.js",
  "jspm": {
    "registry": "jspm",
    "directories": {
      "baseURL": "src"
    },
    "devDependencies": {
      "traceur": "github:jmcriffey/bower-traceur@0.0.87",
      "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.87"
    }
  }
}

```

/bar/index.js
```js
import "foo";
```
```
$ cd /foo
$ jspm link
$ cd /bar
$ jspm install --link foo
$ jspm bundle-sfx index

err  Error: Error loading "jspm:foo@0.0.0" at file:/bar/jspm_packages/jspm/foo@0.0.0.js
     Error loading "jspm:foo@0.0.0" from "index" at file:/bar/index.js
     ENOENT, open '/bar/jspm_packages/jspm/foo@0.0.0.js'
         at Error (native)

```

**Comment by guybedford** [comment] 2015-03-22 09:59
Yes this should be supported.

**Comment by hgl** [comment] 2015-03-22 10:17
I'm sorry, but not quite sure it's my own mistake or jspm's error?

**Comment by guybedford** [comment] 2015-03-22 10:23
It's a feature that needs to be supported in jspm.

**Comment by guybedford** [comment] 2015-03-22 10:25
That said, we did move away from inferring the local package name entirely as that was somewhat confusing to users expecting that.

Basically the idea is currently that the package name itself isn't handled by jspm at all. So you just require it locally as a normal path.

**Comment by hgl** [comment] 2015-03-22 11:32
Not quite sure I understand the root problem. Isn't there any workaround? Or linking a package with `main` field specified isn't currently possible?

**Comment by guybedford** [comment] 2015-03-22 11:41
Oh sorry I misread this. The issue is that you need to set the main to `src/index.js` otherwise set a `directories.lib: 'src'` and then that will work.

**Comment by hgl** [comment] 2015-03-22 11:45
I tried `src/index.js`:

/foo/package.json
```json
{
  "name": "foo",
  "version": "0.0.0",
  "main": "src/index.js",
  "jspm": {
    "registry": "jspm",
    "directories": {
      "baseURL": "src"
    },
    "devDependencies": {
      "traceur": "github:jmcriffey/bower-traceur@0.0.87",
      "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.87"
    }
  }
}
```

Exact same error.

**Comment by guybedford** [comment] 2015-03-22 11:57
Unfortunately mains don't update properly when relinking installing. Try removing jspm_packages entirely before redoing the `install --link`.

**Comment by hgl** [comment] 2015-03-22 12:05
Hate to say this, but still no luck. I even tried removing `~/.jspm` and `/bar/jspm_packages`, `link`, and `install --link`, `bundle-sfx` still gives the same error:

```
err  Error: Error loading "jspm:foo@0.0.0" at file:/bar/jspm_packages/jspm/foo@0.0.0.js
     Error loading "jspm:foo@0.0.0" from "index" at file:/bar/index.js
     ENOENT, open '/bar/jspm_packages/jspm/foo@0.0.0.js'
         at Error (native)
```

**Comment by guybedford** [comment] 2015-03-22 12:27
Thanks. Fixed in https://github.com/jspm/jspm-cli/commit/1c769d0a1062c0f57e86fa8a1061c76351b2459c.

**Closed** 2015-03-22 12:28 UTC

**Comment by hgl** [comment] 2015-03-22 12:41
Thank you.

**Comment by hgl** [comment] 2015-03-22 12:50
Running `bundle-sfx` now throws:

```
err  TypeError: Cannot read property 'plugin' of undefined
         at /usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/index.js:184:31
         at Array.map (native)
         at buildOutputs (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/index.js:177:28)
         at Builder.buildTree (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/index.js:214:10)
         at /usr/local/lib/node_modules/jspm/lib/bundle.js:93:26
         at tryCatchReject (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
         at runContinuation1 (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
         at Fulfilled.when (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
         at Pending.run (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:821:13)
         at Scheduler._drain (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:97:19)
```

**Comment by guybedford** [comment] 2015-03-22 12:52
You need to run SystemJS, ESML and SystemJS builder all on master against the jspm master release.

**Comment by hgl** [comment] 2015-03-22 13:12
That seems to be challenging. Any ETA for the new jspm release?

**Comment by guybedford** [comment] 2015-03-22 13:27
Tuesday at the latest.

**Comment by hgl** [comment] 2015-03-22 13:37
OK. Thanks for the heads up.
