### ISSUE TITLE
wrong version of Angular is being installed

### ISSUE THREAD

**Issue by capaj** [jspm/jspm-cli#409] opened 2015-01-16 19:59 UTC
when I install angular with jspm 0.10.6(any OS):
```
jspm install angular
     Updating registry cache...
     Looking up github:angular/bower-angular
ok   Up to date - angular as github:angular/bower-angular@^1.3.9 (1.3.9)
     Installed Forks

               github:angular/bower-angular 1.3.0-beta.19 1.3.9
     
     To inspect individual package constraints, use jspm inspect endpoint:name.


ok   Install complete.
```
I would expect version 1.3.9 or 1.4.0-beta.0 to be installed as they are the latest. And the tags on Angular repo seem fine as well.

**Comment by subesokun** [comment] 2015-01-17 09:32
Hi, after having a brief look on it everything seems to be fine imho. The latest stable tag is `v1.3.9` and all other newer versions have the version suffix `-build` or `-beta`, hence they won't be included in the ^1.3.9 version range. If you want to install the 1.4.0-beta then you've to do a `jspm install angular@^1.4.0-beta.0` but you [might need to add a package override](https://github.com/jspm/registry/tree/master/package-overrides/github/angular) for the 1.4.0-beta.x version.
I'm not sure how the registry lookup is implemented at the moment but due semver the version 1.4.0-beta.0 is not part of the [^1.3.0 package override](https://github.com/jspm/registry/blob/master/package-overrides/github/angular/bower-angular%401.3.0.json) range.

Hope that helped you a little bit.

@guybedford What irritates me is that `jspm install angular@~1.3.10-build.7+sha.1f9da20` installs correctly the latest build version e.g. `build.22` but `jspm install angular@^1.3.10-build.7+sha.1f9da20` sticks always to `build.7`. Is that an expected behaviour?

**Comment by guybedford** [comment] 2015-01-18 09:52
@subesokun thanks for clarifying here. I tried `jspm install angular@^1.3.10-build.7+sha.1f9da20`, but it definitely installs to `1.3.10-build.22+sha.13edaa9` for me? Are you running the latest jspm?

**Comment by subesokun** [comment] 2015-01-18 10:10
@guybedford sure, no problem. As issues are piling up I've tried to help out where I can.

Just verified it again and still same behaviour. As info, I've tested it only on a Windows 7 machine.
```
jspm@0.10.6
node@0.10.35
```

```
jspm install angular@^1.3.10-build.7+sha1f9da20
     Updating registry cache...
     Looking up github:angular/bower-angular
ok   Installed angular as github:angular/bower-angular@1.3.10-build.7+sha1f9da20 (1.3.10-build.7+sha.1f9da20)
ok   Install tree has no forks.
```

**Comment by guybedford** [comment] 2015-01-18 14:04
@subesokun I can confirm this is loading 22 if I run the exact same steps. Will test on windows then.

**Comment by guybedford** [comment] 2015-01-27 12:37
@capaj did you get any further with this?

**Comment by guybedford** [comment] 2015-01-30 10:54
I can confirm that this lookup is giving the wrong result in windows. Looking into it.

**Comment by capaj** [comment] 2015-01-30 10:55
@guybedford awesome

**Comment by guybedford** [comment] 2015-01-30 11:00
Sorry, I misread the install output - I'm getting:

```
Up to date - angular as github:angular/bower-angular@^1.3.10-build.7+sha1f9da20 (1.3.11)
```

The version installed is 1.3.11 so this is definitely working ok.

@capaj note that in your example 1.3.9 was the right version as 1.4.0-beta is unstable so won't be installed unless explicitly specified.

**Comment by guybedford** [comment] 2015-01-30 11:00
Closing, but let me know if there are still issues here.

**Closed** 2015-01-30 11:00 UTC
