### ISSUE TITLE
0.17.0-beta-16 throws an error while trying to do a production build

### ISSUE THREAD

**Issue by Palid** [jspm/jspm-cli#1857] opened 2016-05-27 08:21 UTC
```
jspm build app build/app.min.js --minify --no-mangle --skip-source-maps --source-map-contents

     Creating the single-file build for app...

err  TypeError: Cannot read property 'map' of undefined
    at {rest_of_the_path}/app/node_modules/systemjs-builder/lib/trace.js:237:39
```

Looks like it happens also on beta-15 due to some changes in systemjs-builder. Didn't know where to give it, as it's both SystemJS and JSPM related - problem does not exist in the `bundle` command, only in build. Changing flags doesn't fix the problem.

**Comment by Palid** [comment] 2016-05-27 08:39
Alright, I debugged the problem. For some reason it searches for `file:///{rest_of_the_path}/app/src/`while it's `file:///{rest_of_the_path}/app/src` in the loader.packages dictionary. Looks like a bug in the SystemJS normalize.

**Comment by guybedford** [comment] 2016-05-27 10:46
I'd need to see your configuration here to understand what exactly is happening. Please share the relevant info you can.

**Comment by Palid** [comment] 2016-05-27 13:23
@guybedford What kinds of configuration do you need? OS, node, jspm.config files...?

**Comment by perrin4869** [comment] 2016-05-27 15:19
I got the same problem, running:

```
jspm build react-stay-scrolled-demo client.js --minify --no-mangle --skip-source-maps --source-map-contents
```
Inside this dir: https://github.com/perrin4869/react-stay-scrolled/tree/master/examples

**Comment by adamburgess** [comment] 2016-05-30 01:26
>@guybedford: I'd need to see your configuration here

there is no configuration

`npm init -y && npm install --save jspm@beta && jspm init -y && echo console.log('hi')>test.js && jspm build test.js --production`

```
     Creating the single-file build for test.js...

err  TypeError: Error building condition @system-env|production. For static condition inlining only an exact environment resolution can be built, pending https://github.com/systemjs/builder/issues/311.
    at \node_modules\systemjs-builder\lib\trace.js:651:15
    at tryCatcher (\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (\node_modules\bluebird\js\release\promise.js:628:18)
    at Promise._resolveCallback (\node_modules\bluebird\js\release\promise.js:423:57)
    at Promise._settlePromiseFromHandler (\node_modules\bluebird\js\release\promise.js:514:17)
    at Promise._settlePromise (\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (\node_modules\bluebird\js\release\promise.js:683:18)
    at Promise._fulfill (\node_modules\bluebird\js\release\promise.js:628:18)
    at PromiseArray._resolve (\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (\node_modules\bluebird\js\release\promise.js:564:26)
```

**Comment by guybedford** [comment] 2016-05-30 11:32
Ah right thanks for clarifying, I think this was fixed in https://github.com/systemjs/builder/commit/36b9c7c4d9189fe9f1ca6647538d73ff7da8b84e.

**Comment by perrin4869** [comment] 2016-05-30 12:09
thanks a lot @guybedford! do you plan to release a patched version with the fix?

**Comment by perrin4869** [comment] 2016-06-01 02:04
@guybedford this issue was solved by beta17, thanks!
I still got a problem building another project though which built before beta15, I get the following error:

```
{ [Error: Error on fetch for core-js/library/fn/object/keys at file:///home/perrin4869/projects/websites/foo/client/core-js/library/fn/object/keys
        Loading npm:babel-runtime@5.8.38/core-js/object/keys.js
        Loading npm:react-bootstrap@0.29.4/lib/Modal.js
        Loading foo/components/app.jsx
        Loading foo/components/routes.jsx
        Loading foo/main.jsx
        ENOENT: no such file or directory, open '/home/perrin4869/projects/websites/foo/client/core-js/library/fn/object/keys']
  originalErr: 
   { [Error: ENOENT: no such file or directory, open '/home/perrin4869/projects/websites/foo/client/core-js/library/fn/object/keys']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/home/perrin4869/projects/websites/foo/client/core-js/library/fn/object/keys' } }
```

I think that it is related to the project structure in this one. From my `package.json`:

```json
{
  "jspm": {
    "directories": {
      "baseURL": "client",
      "lib": "client/js"
    }
}
```

I have all my client related files in a `client` subdir, including `jspm_packages`, `jspm.config.js`, `jspm.browser.js`, etc... which is throwing the builder off track when looking for packages.

**Comment by Palid** [comment] 2016-06-01 06:51
@perrin4869 Same, for me it can't find sourcemaps for react-intl. ;)

**Comment by guybedford** [comment] 2016-06-01 10:45
@perrin4869 I think that was an older SystemJS bug - are you definitely using the latest version of SystemJS there?

**Comment by perrin4869** [comment] 2016-06-01 11:09
How do I check? I updated the jspm version in package.json and ran npm
update jspm, so I should be using the latest

**Comment by guybedford** [comment] 2016-06-01 11:13
Look at the version at the top of jspm_packages/system.src.js, or check System.version.

**Comment by perrin4869** [comment] 2016-06-01 15:09
Here it is, seems to be in order as expected:

```bash
$ head -3 client/jspm_packages/system.src.js
/*
 * SystemJS v0.19.29
 */
```

**Comment by guybedford** [comment] 2016-06-01 16:50
@perrin4869 can you share a simple test case here? What install should I do to replicate? `jspm install core-js && jspm run core-js/library/fn/object/keys` doesn't seem to catch it.

**Comment by perrin4869** [comment] 2016-06-02 00:10
I will try to reproduce the error later. I suspect however that it has to
do with the directory structure, since other projects where `jspm_packages`
is at the root of the project build without problem.

**Comment by perrin4869** [comment] 2016-06-02 12:16
Trying to reproduce now, I noticed that `jspm init` no longer generates `jspm.browser.config`. Has it been deprecated? How do you migrate the existing `jspm.browser.config`?

**Comment by guybedford** [comment] 2016-06-02 13:13
On the latest beta, it is still supported as package.json configFiles.jspm:browser property.

**Comment by perrin4869** [comment] 2016-06-04 16:44
ended up reconfiguring jspm from zero, and after some fiddling around, problem got solved! not sure what caused it though. I think it was that system.js couldn't locate the jspm_packages directory

**Comment by perrin4869** [comment] 2016-06-10 00:38
@guybedford I think this can be safely closed now

**Comment by guybedford** [comment] 2016-06-10 00:40
Sure, thanks!

**Closed by guybedford** 2016-06-10 00:40 UTC
